import { Topic } from './types';

export const anatomy: Topic = {
  id: 'anatomy',
  title: 'Anatomy',
  shortTitle: 'Anatomy',
  description: 'Bones, muscles, joints, and innervation',
  icon: '🦴',
  color: '#58CC02',
  units: [
    {
      id: 'anatomy-u1',
      title: 'Unit 1: Terminology, Tissues, Joints',
      lessons: [
        {
          id: 'anatomy-u1-l1',
          title: 'Anatomical Terminology',
          questions: [
            {
              id: 'anatomy-u1-l1-q1',
              type: 'mcq',
              prompt: 'What is the reference position used as the basis for all anatomical directional terms?',
              options: ['Supine position', 'Anatomical position', 'Fetal position', 'Neutral position'],
              correctIndex: 1,
              explanation: 'The anatomical position is the standard reference point for describing the body.',
            },
            {
              id: 'anatomy-u1-l1-q2',
              type: 'mcq',
              prompt: 'Which term means the same as "cranial"?',
              options: ['Inferior', 'Superior', 'Proximal', 'Anterior'],
              correctIndex: 1,
              explanation: 'Superior/inferior are relative to the head/feet, also termed cranial/caudal.',
            },
            {
              id: 'anatomy-u1-l1-q3',
              type: 'mcq',
              prompt: 'Which term means the same as "ventral"?',
              options: ['Posterior', 'Anterior', 'Superficial', 'Medial'],
              correctIndex: 1,
              explanation: 'Anterior/posterior are also termed ventral/dorsal.',
            },
            {
              id: 'anatomy-u1-l1-q4',
              type: 'mcq',
              prompt: "A structure described as 'intermediate' is located:",
              options: [
                'Farther from the trunk than another structure',
                'Between a superficial and a deep structure',
                'Closer to the median plane',
                'Along the long axis of the body',
              ],
              correctIndex: 1,
              explanation: 'Intermediate describes a position between superficial and deep structures.',
            },
            {
              id: 'anatomy-u1-l1-q5',
              type: 'mcq',
              prompt: 'Which anatomical plane divides the body into anterior and posterior parts?',
              options: ['Median (sagittal) plane', 'Frontal (coronal) plane', 'Transverse (axial) plane', 'Oblique section'],
              correctIndex: 1,
              explanation: 'The frontal (coronal) plane divides the body into anterior and posterior portions.',
            },
            {
              id: 'anatomy-u1-l1-q6',
              type: 'true-false',
              prompt: 'The transverse (axial) plane divides the body into right and left halves.',
              correctAnswer: false,
              explanation: 'The transverse plane divides the body into superior and inferior parts; the median (sagittal) plane divides right and left.',
            },
            {
              id: 'anatomy-u1-l1-q7',
              type: 'mcq',
              prompt: 'A cut made along the long axis of a structure is called a:',
              options: ['Transverse section', 'Oblique section', 'Longitudinal section', 'Coronal section'],
              correctIndex: 2,
              explanation: 'A longitudinal section is a cut along the long axis; an oblique section is a cut made at an angle.',
            },
            {
              id: 'anatomy-u1-l1-q8',
              type: 'mcq',
              prompt: 'Proximal/distal terminology is most commonly used to describe position along the:',
              options: ['Trunk', 'Limbs', 'Skull', 'Spine'],
              correctIndex: 1,
              explanation: 'Proximal/distal are relative to the trunk or point of origin, most commonly applied to the limbs.',
            },
            {
              id: 'anatomy-u1-l1-q9',
              type: 'mcq',
              prompt: 'Which directional term describes the palm side of the hand?',
              options: ['Dorsal', 'Palmar', 'Plantar', 'Volar-distal'],
              correctIndex: 1,
              explanation: 'Palmar refers specifically to the palm of the hand (as opposed to dorsal, the back of the hand).',
            },
            {
              id: 'anatomy-u1-l1-q10',
              type: 'mcq',
              prompt: 'Which directional term describes the sole of the foot?',
              options: ['Dorsal', 'Palmar', 'Plantar', 'Inferior-distal'],
              correctIndex: 2,
              explanation: 'Plantar refers specifically to the sole of the foot (as opposed to dorsal, the top of the foot).',
            },
          ],
        },
        {
          id: 'anatomy-u1-l2',
          title: 'Tissues',
          questions: [
            {
              id: 'anatomy-u1-l2-q1',
              type: 'mcq',
              prompt: 'Besides how they are layered (simple, stratified, pseudostratified), epithelial tissue is also classified by:',
              options: ['Vascularity', 'Cell shape (squamous, cuboidal, columnar)', 'Embryological origin', 'Collagen content'],
              correctIndex: 1,
              explanation: 'Epithelial tissue is classified by both the number of layers and the shape of its cells.',
            },
            {
              id: 'anatomy-u1-l2-q2',
              type: 'mcq',
              prompt: 'All connective tissue shares a common embryological origin from:',
              options: ['Ectoderm', 'Endoderm', 'Mesenchyme', 'Neural crest only'],
              correctIndex: 2,
              explanation: 'All connective tissue types derive from mesenchyme.',
            },
            {
              id: 'anatomy-u1-l2-q3',
              type: 'multi-select',
              prompt: "Which of the following are classified as 'loose' connective tissue proper?",
              options: ['Areolar tissue', 'Adipose tissue', 'Reticular tissue', 'Dense regular tissue'],
              correctIndices: [0, 1, 2],
              explanation: 'Loose connective tissue proper includes areolar, adipose, and reticular tissue; dense regular tissue belongs to the dense category.',
            },
            {
              id: 'anatomy-u1-l2-q4',
              type: 'multi-select',
              prompt: "Which of the following are classified as 'supporting' connective tissue?",
              options: ['Hyaline cartilage', 'Fibrocartilage', 'Compact bone', 'Blood'],
              correctIndices: [0, 1, 2],
              explanation: 'Supporting connective tissue includes cartilage (hyaline, fibrocartilage, elastic) and bone (compact, spongy); blood is fluid connective tissue.',
            },
            {
              id: 'anatomy-u1-l2-q5',
              type: 'mcq',
              prompt: 'Blood and lymph are classified as which type of connective tissue?',
              options: ['Connective tissue proper', 'Supporting connective tissue', 'Fluid connective tissue', 'Reticular connective tissue'],
              correctIndex: 2,
              explanation: 'Blood and lymph make up the fluid connective tissue category.',
            },
            {
              id: 'anatomy-u1-l2-q6',
              type: 'true-false',
              prompt: 'Cartilage has a rich blood supply, which allows it to heal quickly after injury.',
              correctAnswer: false,
              explanation: 'Cartilage has no blood supply at all, which is why cartilage injuries heal slowly.',
            },
            {
              id: 'anatomy-u1-l2-q7',
              type: 'mcq',
              prompt: 'Skeletal and cardiac muscle are both classified as:',
              options: ['Smooth muscle', 'Striated muscle', 'Visceral muscle', 'Involuntary muscle only'],
              correctIndex: 1,
              explanation: 'Striated muscle includes both skeletal and cardiac muscle; smooth muscle is also called visceral muscle.',
            },
            {
              id: 'anatomy-u1-l2-q8',
              type: 'mcq',
              prompt: 'The epidermis is composed of:',
              options: [
                'Dense irregular connective tissue',
                'Keratinized stratified squamous epithelium',
                'Areolar and adipose connective tissue',
                'Simple columnar epithelium',
              ],
              correctIndex: 1,
              explanation: 'The epidermis is keratinized stratified squamous epithelium, organized into five strata.',
            },
            {
              id: 'anatomy-u1-l2-q9',
              type: 'mcq',
              prompt: 'Which layer of the dermis is deeper, makes up the major portion of the dermis, and is composed of dense irregular connective tissue with lines of cleavage?',
              options: ['Papillary layer', 'Reticular layer', 'Basal layer', 'Hypodermis'],
              correctIndex: 1,
              explanation: 'The reticular layer is the deeper, major portion of the dermis; the papillary layer is superficial and contains dermal papillae.',
            },
            {
              id: 'anatomy-u1-l2-q10',
              type: 'fill-blank',
              prompt: 'The hypodermis (subcutaneous layer) is composed of areolar and ______ connective tissue.',
              acceptedAnswers: ['adipose'],
              explanation: 'The hypodermis is areolar and adipose connective tissue, providing protection, energy storage, and insulation.',
            },
            {
              id: 'anatomy-u1-l2-q11',
              type: 'mcq',
              prompt: 'The hypodermis is a common site for drug injections primarily because it is:',
              options: ['Avascular', 'Extensively vascularized', 'Composed of dense regular tissue', 'Part of the epidermis'],
              correctIndex: 1,
              explanation: 'The hypodermis is extensively vascularized, which allows for efficient drug absorption after subcutaneous injection.',
            },
          ],
        },
        {
          id: 'anatomy-u1-l3',
          title: 'Joints & Movement',
          questions: [
            {
              id: 'anatomy-u1-l3-q1',
              type: 'mcq',
              prompt: 'A skull suture, held together by dense connective tissue, is an example of which structural joint classification?',
              options: ['Fibrous joint', 'Cartilaginous joint', 'Synovial joint', 'Diarthrosis'],
              correctIndex: 0,
              explanation: 'Fibrous joints, such as sutures, are held together by dense connective tissue.',
            },
            {
              id: 'anatomy-u1-l3-q2',
              type: 'mcq',
              prompt: 'An intervertebral joint, joined by cartilage, is structurally classified as a:',
              options: ['Fibrous joint', 'Cartilaginous joint', 'Synovial joint', 'Synarthrosis by definition'],
              correctIndex: 1,
              explanation: 'Cartilaginous joints, such as intervertebral joints, are joined by cartilage.',
            },
            {
              id: 'anatomy-u1-l3-q3',
              type: 'mcq',
              prompt: 'The shoulder and knee, which have a fluid-filled joint cavity separating the bones, are structurally classified as:',
              options: ['Fibrous joints', 'Cartilaginous joints', 'Synovial joints', 'Amphiarthroses'],
              correctIndex: 2,
              explanation: 'Synovial joints have a fluid-filled joint cavity separating the articulating bones.',
            },
            {
              id: 'anatomy-u1-l3-q4',
              type: 'mcq',
              prompt: 'Functionally, a freely mobile joint is classified as a(n):',
              options: ['Synarthrosis', 'Amphiarthrosis', 'Diarthrosis', 'Symphysis'],
              correctIndex: 2,
              explanation: 'Diarthroses are freely mobile joints.',
            },
            {
              id: 'anatomy-u1-l3-q5',
              type: 'mcq',
              prompt: 'Functionally, an immobile joint is classified as a(n):',
              options: ['Synarthrosis', 'Amphiarthrosis', 'Diarthrosis', 'Synovial joint'],
              correctIndex: 0,
              explanation: 'Synarthroses are immobile joints; amphiarthroses are slightly mobile.',
            },
            {
              id: 'anatomy-u1-l3-q6',
              type: 'multi-select',
              prompt: 'Which of the following are basic components of a synovial joint?',
              options: ['Articular capsule', 'Synovial fluid', 'Ligaments', 'A perichondrium covering the cartilage'],
              correctIndices: [0, 1, 2],
              explanation: 'Synovial joints include an articular capsule, synovial fluid, articular cartilage, ligaments, nerves, and blood vessels — but articular cartilage specifically lacks a perichondrium.',
            },
            {
              id: 'anatomy-u1-l3-q7',
              type: 'true-false',
              prompt: 'Articular cartilage has its own perichondrium and blood supply.',
              correctAnswer: false,
              explanation: 'Articular cartilage (hyaline cartilage) lacks a perichondrium and is avascular.',
            },
            {
              id: 'anatomy-u1-l3-q8',
              type: 'mcq',
              prompt: "The synovial membrane's primary function is to:",
              options: [
                'Absorb shock directly between bones',
                'Produce synovial fluid that lubricates and nourishes the joint',
                'Anchor tendons to bone',
                'Form the joint capsule\'s outer fibrous layer',
              ],
              correctIndex: 1,
              explanation: 'The synovial membrane produces synovial fluid, which lubricates and nourishes the joint.',
            },
            {
              id: 'anatomy-u1-l3-q9',
              type: 'true-false',
              prompt: 'In general, the more stable a joint is, the more mobile it tends to be.',
              correctAnswer: false,
              explanation: 'There is a trade-off between mobility and stability: the more stable a joint is, the less mobile it is.',
            },
            {
              id: 'anatomy-u1-l3-q10',
              type: 'mcq',
              prompt: 'Of the following joint shapes, which is generally the MOST mobile?',
              options: ['Plane joint', 'Hinge joint', 'Saddle joint', 'Ball-and-socket joint'],
              correctIndex: 3,
              explanation: 'From least to most mobile: plane, hinge, pivot, condylar, saddle, ball-and-socket.',
            },
            {
              id: 'anatomy-u1-l3-q11',
              type: 'mcq',
              prompt: 'A muscle contraction that produces force without any visible joint movement is called:',
              options: ['Isometric', 'Concentric', 'Eccentric', 'Isotonic-shortening'],
              correctIndex: 0,
              explanation: 'Isometric contractions produce force without movement; concentric contractions shorten the muscle and eccentric contractions lengthen it.',
            },
            {
              id: 'anatomy-u1-l3-q12',
              type: 'mcq',
              prompt: 'The muscle that acts as the prime mover of a movement is called the:',
              options: ['Antagonist', 'Synergist', 'Fixator', 'Agonist'],
              correctIndex: 3,
              explanation: 'The agonist is the prime mover; the antagonist opposes the movement, the synergist assists, and the fixator stabilizes.',
            },
          ],
        },
      ],
    },
    { id: 'anatomy-u2', title: 'Unit 2: The Back, Vertebral Column, Musculature', lessons: [{ id: 'anatomy-u2-l1', title: 'Unit 2: The Back, Vertebral Column, Musculature', questions: [] }] },
    { id: 'anatomy-u3', title: 'Unit 3: Posterior Cervical Triangle, Axillary Region', lessons: [{ id: 'anatomy-u3-l1', title: 'Unit 3: Posterior Cervical Triangle, Axillary Region', questions: [] }] },
    { id: 'anatomy-u4', title: 'Unit 4: Axioappendicular Muscles, Shoulder Joint', lessons: [{ id: 'anatomy-u4-l1', title: 'Unit 4: Axioappendicular Muscles, Shoulder Joint', questions: [] }] },
    { id: 'anatomy-u5', title: 'Unit 5: The Arm, Elbow, Cubital Fossa', lessons: [{ id: 'anatomy-u5-l1', title: 'Unit 5: The Arm, Elbow, Cubital Fossa', questions: [] }] },
    { id: 'anatomy-u6', title: 'Unit 6: Forearm, Wrist', lessons: [{ id: 'anatomy-u6-l1', title: 'Unit 6: Forearm, Wrist', questions: [] }] },
    { id: 'anatomy-u7', title: 'Unit 7: The Hand', lessons: [{ id: 'anatomy-u7-l1', title: 'Unit 7: The Hand', questions: [] }] },
    { id: 'anatomy-u8', title: 'Unit 8: Anterior Neck, Face, TMJ', lessons: [{ id: 'anatomy-u8-l1', title: 'Unit 8: Anterior Neck, Face, TMJ', questions: [] }] },
    { id: 'anatomy-u9', title: 'Unit 9: The Thorax', lessons: [{ id: 'anatomy-u9-l1', title: 'Unit 9: The Thorax', questions: [] }] },
    { id: 'anatomy-u10', title: 'Unit 10: Abdominal Wall, Viscera, Vasculature', lessons: [{ id: 'anatomy-u10-l1', title: 'Unit 10: Abdominal Wall, Viscera, Vasculature', questions: [] }] },
    { id: 'anatomy-u11', title: 'Unit 11: Posterior Abdominal Wall, Pelvis, Gluteal Region', lessons: [{ id: 'anatomy-u11-l1', title: 'Unit 11: Posterior Abdominal Wall, Pelvis, Gluteal Region', questions: [] }] },
    { id: 'anatomy-u12', title: 'Unit 12: Hip, Thigh, Knee', lessons: [{ id: 'anatomy-u12-l1', title: 'Unit 12: Hip, Thigh, Knee', questions: [] }] },
    { id: 'anatomy-u13', title: 'Unit 13: Leg, Foot, Ankle', lessons: [{ id: 'anatomy-u13-l1', title: 'Unit 13: Leg, Foot, Ankle', questions: [] }] },
  ],
};
