import { Topic } from './types';

export const anatomy: Topic = {
  id: 'anatomy',
  title: 'Anatomy',
  shortTitle: 'Anatomy',
  description: 'Bones, muscles, joints, and innervation',
  icon: '🦴',
  color: '#58CC02',
  lessons: [
    {
      id: 'anatomy-1',
      title: 'Unit 1: Terminology, Tissues, Joints',
      questions: [
        {
          id: 'anatomy-1-1',
          type: 'mcq',
          prompt: 'Which anatomical plane divides the body into anterior and posterior parts?',
          options: ['Median (sagittal) plane', 'Frontal (coronal) plane', 'Transverse (axial) plane', 'Oblique section'],
          correctIndex: 1,
          explanation: 'The frontal (coronal) plane divides the body into anterior and posterior portions.',
        },
        {
          id: 'anatomy-1-2',
          type: 'mcq',
          prompt: "A structure described as 'proximal' is located:",
          options: [
            'Closer to the surface of the body',
            'Closer to the trunk or point of origin of a limb',
            'Closer to the midline',
            'Farther from the trunk',
          ],
          correctIndex: 1,
          explanation: 'Proximal/distal describe position relative to the trunk or point of origin, most commonly used for the limbs.',
        },
        {
          id: 'anatomy-1-3',
          type: 'mcq',
          prompt: "Which directional term describes the sole of the foot, analogous to 'palmar' for the hand?",
          options: ['Dorsal', 'Plantar', 'Ventral', 'Volar'],
          correctIndex: 1,
          explanation: 'Plantar refers to the sole of the foot, just as palmar refers to the palm of the hand.',
        },
        {
          id: 'anatomy-1-4',
          type: 'true-false',
          prompt: 'The transverse (axial) plane divides the body into right and left halves.',
          correctAnswer: false,
          explanation: 'The transverse plane divides the body into superior and inferior parts; the median (sagittal) plane divides right and left.',
        },
        {
          id: 'anatomy-1-5',
          type: 'mcq',
          prompt: 'Which tissue type is composed of closely packed cells with little extracellular matrix, and covers body surfaces and lines cavities?',
          options: ['Connective tissue', 'Muscle tissue', 'Epithelial tissue', 'Nervous tissue'],
          correctIndex: 2,
          explanation: 'Epithelial tissue is characterized by closely packed cells and covers surfaces, lines cavities/passageways, and forms glands.',
        },
        {
          id: 'anatomy-1-6',
          type: 'multi-select',
          prompt: "Which of the following are classified as 'connective tissue proper'?",
          options: ['Loose areolar tissue', 'Adipose tissue', 'Hyaline cartilage', 'Dense regular tissue', 'Bone'],
          correctIndices: [0, 1, 3],
          explanation: 'Connective tissue proper includes loose (areolar, adipose, reticular) and dense (regular, irregular, elastic) types. Cartilage and bone are classified as supporting connective tissue.',
        },
        {
          id: 'anatomy-1-7',
          type: 'true-false',
          prompt: 'Tendons and ligaments are highly vascular and generally heal quickly after injury.',
          correctAnswer: false,
          explanation: 'Most connective tissue is highly vascular, but tendons and ligaments have a poor blood supply (and cartilage has none), so they heal slowly.',
        },
        {
          id: 'anatomy-1-8',
          type: 'mcq',
          prompt: 'Which layer of the dermis contains dermal papillae that interlock with the epidermal ridges?',
          options: ['Papillary layer', 'Reticular layer', 'Subcutaneous layer', 'Stratum corneum'],
          correctIndex: 0,
          explanation: 'The papillary layer is the superficial layer of the dermis, made of areolar connective tissue with dermal papillae.',
        },
        {
          id: 'anatomy-1-9',
          type: 'fill-blank',
          prompt: 'The layer beneath the dermis, made of areolar and adipose connective tissue and commonly used as a site for drug injections, is called the ______.',
          acceptedAnswers: ['hypodermis', 'subcutaneous layer', 'subcutaneous tissue'],
          explanation: 'The hypodermis (subcutaneous layer) provides protection, energy storage, and insulation, and is not technically part of the integument.',
        },
        {
          id: 'anatomy-1-10',
          type: 'mcq',
          prompt: 'A joint held together by dense connective tissue, such as a skull suture, is structurally classified as a:',
          options: ['Fibrous joint', 'Cartilaginous joint', 'Synovial joint', 'Diarthrotic joint'],
          correctIndex: 0,
          explanation: 'Fibrous joints, such as sutures, are held together by dense connective tissue.',
        },
        {
          id: 'anatomy-1-11',
          type: 'mcq',
          prompt: 'A freely mobile joint, such as the shoulder, is functionally classified as a:',
          options: ['Synarthrosis', 'Amphiarthrosis', 'Diarthrosis', 'Symphysis'],
          correctIndex: 2,
          explanation: 'Diarthroses are freely mobile joints; synarthroses are immobile and amphiarthroses are slightly mobile.',
        },
        {
          id: 'anatomy-1-12',
          type: 'mcq',
          prompt: 'A muscle contraction in which the muscle shortens while generating force to produce movement is called:',
          options: ['Isometric', 'Concentric', 'Eccentric', 'Isotonic-static'],
          correctIndex: 1,
          explanation: 'Concentric contractions shorten the muscle; eccentric contractions lengthen it under tension; isometric contractions produce no movement.',
        },
      ],
    },
    {
      id: 'anatomy-2',
      title: 'Unit 2: The Back, Vertebral Column, Musculature',
      questions: [],
    },
    {
      id: 'anatomy-3',
      title: 'Unit 3: Posterior Cervical Triangle, Axillary Region',
      questions: [],
    },
    {
      id: 'anatomy-4',
      title: 'Unit 4: Axioappendicular Muscles, Shoulder Joint',
      questions: [],
    },
    {
      id: 'anatomy-5',
      title: 'Unit 5: The Arm, Elbow, Cubital Fossa',
      questions: [],
    },
    {
      id: 'anatomy-6',
      title: 'Unit 6: Forearm, Wrist',
      questions: [],
    },
    {
      id: 'anatomy-7',
      title: 'Unit 7: The Hand',
      questions: [],
    },
    {
      id: 'anatomy-8',
      title: 'Unit 8: Anterior Neck, Face, TMJ',
      questions: [],
    },
    {
      id: 'anatomy-9',
      title: 'Unit 9: The Thorax',
      questions: [],
    },
    {
      id: 'anatomy-10',
      title: 'Unit 10: Abdominal Wall, Viscera, Vasculature',
      questions: [],
    },
    {
      id: 'anatomy-11',
      title: 'Unit 11: Posterior Abdominal Wall, Pelvis, Gluteal Region',
      questions: [],
    },
    {
      id: 'anatomy-12',
      title: 'Unit 12: Hip, Thigh, Knee',
      questions: [],
    },
    {
      id: 'anatomy-13',
      title: 'Unit 13: Leg, Foot, Ankle',
      questions: [],
    },
  ],
};
