import { Topic } from './types';

export const anatomy: Topic = {
  id: 'anatomy',
  title: 'Anatomy',
  shortTitle: 'Anatomy',
  description: 'Bones, muscles, joints, and innervation',
  icon: '🦴',
  color: '#58CC02',
  units: [
    {
      id: 'anatomy-u1',
      title: 'Unit 1: Terminology, Tissues, Joints',
      lessons: [
        {
          id: 'anatomy-u1-l1',
          title: 'Anatomical Terminology',
          questions: [
            {
              id: 'anatomy-u1-l1-q1',
              type: 'mcq',
              prompt: 'What is the reference position used as the basis for all anatomical directional terms?',
              options: ['Supine position', 'Anatomical position', 'Fetal position', 'Neutral position'],
              correctIndex: 1,
              explanation: 'The anatomical position is the standard reference point for describing the body.',
            },
            {
              id: 'anatomy-u1-l1-q2',
              type: 'mcq',
              prompt: 'Which term means the same as "cranial"?',
              options: ['Inferior', 'Superior', 'Proximal', 'Anterior'],
              correctIndex: 1,
              explanation: 'Superior/inferior are relative to the head/feet, also termed cranial/caudal.',
            },
            {
              id: 'anatomy-u1-l1-q3',
              type: 'mcq',
              prompt: 'Which term means the same as "ventral"?',
              options: ['Posterior', 'Anterior', 'Superficial', 'Medial'],
              correctIndex: 1,
              explanation: 'Anterior/posterior are also termed ventral/dorsal.',
            },
            {
              id: 'anatomy-u1-l1-q4',
              type: 'mcq',
              prompt: "A structure described as 'intermediate' is located:",
              options: [
                'Farther from the trunk than another structure',
                'Between a superficial and a deep structure',
                'Closer to the median plane',
                'Along the long axis of the body',
              ],
              correctIndex: 1,
              explanation: 'Intermediate describes a position between superficial and deep structures.',
            },
            {
              id: 'anatomy-u1-l1-q5',
              type: 'mcq',
              prompt: 'Which anatomical plane divides the body into anterior and posterior parts?',
              options: ['Median (sagittal) plane', 'Frontal (coronal) plane', 'Transverse (axial) plane', 'Oblique section'],
              correctIndex: 1,
              explanation: 'The frontal (coronal) plane divides the body into anterior and posterior portions.',
            },
            {
              id: 'anatomy-u1-l1-q6',
              type: 'true-false',
              prompt: 'The transverse (axial) plane divides the body into right and left halves.',
              correctAnswer: false,
              explanation: 'The transverse plane divides the body into superior and inferior parts; the median (sagittal) plane divides right and left.',
            },
            {
              id: 'anatomy-u1-l1-q7',
              type: 'mcq',
              prompt: 'A cut made along the long axis of a structure is called a:',
              options: ['Transverse section', 'Oblique section', 'Longitudinal section', 'Coronal section'],
              correctIndex: 2,
              explanation: 'A longitudinal section is a cut along the long axis; an oblique section is a cut made at an angle.',
            },
            {
              id: 'anatomy-u1-l1-q8',
              type: 'mcq',
              prompt: 'Proximal/distal terminology is most commonly used to describe position along the:',
              options: ['Trunk', 'Limbs', 'Skull', 'Spine'],
              correctIndex: 1,
              explanation: 'Proximal/distal are relative to the trunk or point of origin, most commonly applied to the limbs.',
            },
            {
              id: 'anatomy-u1-l1-q9',
              type: 'mcq',
              prompt: 'Which directional term describes the palm side of the hand?',
              options: ['Dorsal', 'Palmar', 'Plantar', 'Volar-distal'],
              correctIndex: 1,
              explanation: 'Palmar refers specifically to the palm of the hand (as opposed to dorsal, the back of the hand).',
            },
            {
              id: 'anatomy-u1-l1-q10',
              type: 'mcq',
              prompt: 'Which directional term describes the sole of the foot?',
              options: ['Dorsal', 'Palmar', 'Plantar', 'Inferior-distal'],
              correctIndex: 2,
              explanation: 'Plantar refers specifically to the sole of the foot (as opposed to dorsal, the top of the foot).',
            },
          ],
        },
        {
          id: 'anatomy-u1-l2',
          title: 'Tissues',
          questions: [
            {
              id: 'anatomy-u1-l2-q1',
              type: 'mcq',
              prompt: 'Besides how they are layered (simple, stratified, pseudostratified), epithelial tissue is also classified by:',
              options: ['Vascularity', 'Cell shape (squamous, cuboidal, columnar)', 'Embryological origin', 'Collagen content'],
              correctIndex: 1,
              explanation: 'Epithelial tissue is classified by both the number of layers and the shape of its cells.',
            },
            {
              id: 'anatomy-u1-l2-q2',
              type: 'mcq',
              prompt: 'All connective tissue shares a common embryological origin from:',
              options: ['Ectoderm', 'Endoderm', 'Mesenchyme', 'Neural crest only'],
              correctIndex: 2,
              explanation: 'All connective tissue types derive from mesenchyme.',
            },
            {
              id: 'anatomy-u1-l2-q3',
              type: 'multi-select',
              prompt: "Which of the following are classified as 'loose' connective tissue proper?",
              options: ['Areolar tissue', 'Adipose tissue', 'Reticular tissue', 'Dense regular tissue'],
              correctIndices: [0, 1, 2],
              explanation: 'Loose connective tissue proper includes areolar, adipose, and reticular tissue; dense regular tissue belongs to the dense category.',
            },
            {
              id: 'anatomy-u1-l2-q4',
              type: 'multi-select',
              prompt: "Which of the following are classified as 'supporting' connective tissue?",
              options: ['Hyaline cartilage', 'Fibrocartilage', 'Compact bone', 'Blood'],
              correctIndices: [0, 1, 2],
              explanation: 'Supporting connective tissue includes cartilage (hyaline, fibrocartilage, elastic) and bone (compact, spongy); blood is fluid connective tissue.',
            },
            {
              id: 'anatomy-u1-l2-q5',
              type: 'mcq',
              prompt: 'Blood and lymph are classified as which type of connective tissue?',
              options: ['Connective tissue proper', 'Supporting connective tissue', 'Fluid connective tissue', 'Reticular connective tissue'],
              correctIndex: 2,
              explanation: 'Blood and lymph make up the fluid connective tissue category.',
            },
            {
              id: 'anatomy-u1-l2-q6',
              type: 'true-false',
              prompt: 'Cartilage has a rich blood supply, which allows it to heal quickly after injury.',
              correctAnswer: false,
              explanation: 'Cartilage has no blood supply at all, which is why cartilage injuries heal slowly.',
            },
            {
              id: 'anatomy-u1-l2-q7',
              type: 'mcq',
              prompt: 'Skeletal and cardiac muscle are both classified as:',
              options: ['Smooth muscle', 'Striated muscle', 'Visceral muscle', 'Involuntary muscle only'],
              correctIndex: 1,
              explanation: 'Striated muscle includes both skeletal and cardiac muscle; smooth muscle is also called visceral muscle.',
            },
            {
              id: 'anatomy-u1-l2-q8',
              type: 'mcq',
              prompt: 'The epidermis is composed of:',
              options: [
                'Dense irregular connective tissue',
                'Keratinized stratified squamous epithelium',
                'Areolar and adipose connective tissue',
                'Simple columnar epithelium',
              ],
              correctIndex: 1,
              explanation: 'The epidermis is keratinized stratified squamous epithelium, organized into five strata.',
            },
            {
              id: 'anatomy-u1-l2-q9',
              type: 'mcq',
              prompt: 'Which layer of the dermis is deeper, makes up the major portion of the dermis, and is composed of dense irregular connective tissue with lines of cleavage?',
              options: ['Papillary layer', 'Reticular layer', 'Basal layer', 'Hypodermis'],
              correctIndex: 1,
              explanation: 'The reticular layer is the deeper, major portion of the dermis; the papillary layer is superficial and contains dermal papillae.',
            },
            {
              id: 'anatomy-u1-l2-q10',
              type: 'fill-blank',
              prompt: 'The hypodermis (subcutaneous layer) is composed of areolar and ______ connective tissue.',
              acceptedAnswers: ['adipose'],
              explanation: 'The hypodermis is areolar and adipose connective tissue, providing protection, energy storage, and insulation.',
            },
            {
              id: 'anatomy-u1-l2-q11',
              type: 'mcq',
              prompt: 'The hypodermis is a common site for drug injections primarily because it is:',
              options: ['Avascular', 'Extensively vascularized', 'Composed of dense regular tissue', 'Part of the epidermis'],
              correctIndex: 1,
              explanation: 'The hypodermis is extensively vascularized, which allows for efficient drug absorption after subcutaneous injection.',
            },
          ],
        },
        {
          id: 'anatomy-u1-l3',
          title: 'Joints & Movement',
          questions: [
            {
              id: 'anatomy-u1-l3-q1',
              type: 'mcq',
              prompt: 'A skull suture, held together by dense connective tissue, is an example of which structural joint classification?',
              options: ['Fibrous joint', 'Cartilaginous joint', 'Synovial joint', 'Diarthrosis'],
              correctIndex: 0,
              explanation: 'Fibrous joints, such as sutures, are held together by dense connective tissue.',
            },
            {
              id: 'anatomy-u1-l3-q2',
              type: 'mcq',
              prompt: 'An intervertebral joint, joined by cartilage, is structurally classified as a:',
              options: ['Fibrous joint', 'Cartilaginous joint', 'Synovial joint', 'Synarthrosis by definition'],
              correctIndex: 1,
              explanation: 'Cartilaginous joints, such as intervertebral joints, are joined by cartilage.',
            },
            {
              id: 'anatomy-u1-l3-q3',
              type: 'mcq',
              prompt: 'The shoulder and knee, which have a fluid-filled joint cavity separating the bones, are structurally classified as:',
              options: ['Fibrous joints', 'Cartilaginous joints', 'Synovial joints', 'Amphiarthroses'],
              correctIndex: 2,
              explanation: 'Synovial joints have a fluid-filled joint cavity separating the articulating bones.',
            },
            {
              id: 'anatomy-u1-l3-q4',
              type: 'mcq',
              prompt: 'Functionally, a freely mobile joint is classified as a(n):',
              options: ['Synarthrosis', 'Amphiarthrosis', 'Diarthrosis', 'Symphysis'],
              correctIndex: 2,
              explanation: 'Diarthroses are freely mobile joints.',
            },
            {
              id: 'anatomy-u1-l3-q5',
              type: 'mcq',
              prompt: 'Functionally, an immobile joint is classified as a(n):',
              options: ['Synarthrosis', 'Amphiarthrosis', 'Diarthrosis', 'Synovial joint'],
              correctIndex: 0,
              explanation: 'Synarthroses are immobile joints; amphiarthroses are slightly mobile.',
            },
            {
              id: 'anatomy-u1-l3-q6',
              type: 'multi-select',
              prompt: 'Which of the following are basic components of a synovial joint?',
              options: ['Articular capsule', 'Synovial fluid', 'Ligaments', 'A perichondrium covering the cartilage'],
              correctIndices: [0, 1, 2],
              explanation: 'Synovial joints include an articular capsule, synovial fluid, articular cartilage, ligaments, nerves, and blood vessels — but articular cartilage specifically lacks a perichondrium.',
            },
            {
              id: 'anatomy-u1-l3-q7',
              type: 'true-false',
              prompt: 'Articular cartilage has its own perichondrium and blood supply.',
              correctAnswer: false,
              explanation: 'Articular cartilage (hyaline cartilage) lacks a perichondrium and is avascular.',
            },
            {
              id: 'anatomy-u1-l3-q8',
              type: 'mcq',
              prompt: "The synovial membrane's primary function is to:",
              options: [
                'Absorb shock directly between bones',
                'Produce synovial fluid that lubricates and nourishes the joint',
                'Anchor tendons to bone',
                'Form the joint capsule\'s outer fibrous layer',
              ],
              correctIndex: 1,
              explanation: 'The synovial membrane produces synovial fluid, which lubricates and nourishes the joint.',
            },
            {
              id: 'anatomy-u1-l3-q9',
              type: 'true-false',
              prompt: 'In general, the more stable a joint is, the more mobile it tends to be.',
              correctAnswer: false,
              explanation: 'There is a trade-off between mobility and stability: the more stable a joint is, the less mobile it is.',
            },
            {
              id: 'anatomy-u1-l3-q10',
              type: 'mcq',
              prompt: 'Of the following joint shapes, which is generally the MOST mobile?',
              options: ['Plane joint', 'Hinge joint', 'Saddle joint', 'Ball-and-socket joint'],
              correctIndex: 3,
              explanation: 'From least to most mobile: plane, hinge, pivot, condylar, saddle, ball-and-socket.',
            },
            {
              id: 'anatomy-u1-l3-q11',
              type: 'mcq',
              prompt: 'A muscle contraction that produces force without any visible joint movement is called:',
              options: ['Isometric', 'Concentric', 'Eccentric', 'Isotonic-shortening'],
              correctIndex: 0,
              explanation: 'Isometric contractions produce force without movement; concentric contractions shorten the muscle and eccentric contractions lengthen it.',
            },
            {
              id: 'anatomy-u1-l3-q12',
              type: 'mcq',
              prompt: 'The muscle that acts as the prime mover of a movement is called the:',
              options: ['Antagonist', 'Synergist', 'Fixator', 'Agonist'],
              correctIndex: 3,
              explanation: 'The agonist is the prime mover; the antagonist opposes the movement, the synergist assists, and the fixator stabilizes.',
            },
          ],
        },
      ],
    },
    {
      id: 'anatomy-u2',
      title: 'Unit 2: The Back, Vertebral Column, Musculature',
      lessons: [
        {
          id: 'anatomy-u2-l1',
          title: 'Vertebral Column & Curvatures',
          questions: [
            {
              id: 'anatomy-u2-l1-q1',
              type: 'mcq',
              prompt: 'Which of the following is NOT one of the five regions of the vertebral column?',
              options: ['Cervical', 'Thoracic', 'Appendicular', 'Lumbar'],
              correctIndex: 2,
              explanation: 'The five vertebral column regions are cervical, thoracic, lumbar, sacral, and coccyx.',
            },
            {
              id: 'anatomy-u2-l1-q2',
              type: 'mcq',
              prompt: 'The primary weight-bearing portion of a typical vertebra is the:',
              options: ['Neural arch', 'Body', 'Lamina', 'Pedicle'],
              correctIndex: 1,
              explanation: 'The vertebral body is the primary weight-bearing portion; the neural arch (pedicles, lamina, processes) surrounds the vertebral foramen.',
            },
            {
              id: 'anatomy-u2-l1-q3',
              type: 'mcq',
              prompt: 'The opening in a vertebra that houses the spinal cord is the:',
              options: ['Intervertebral foramen', 'Vertebral foramen', 'Obturator foramen', 'Transverse foramen'],
              correctIndex: 1,
              explanation: 'The vertebral foramen is the opening for the spinal cord, formed by the body and neural arch.',
            },
            {
              id: 'anatomy-u2-l1-q4',
              type: 'mcq',
              prompt: 'Which cervical vertebra is known as the Atlas and articulates with the occipital condyles?',
              options: ['C1', 'C2', 'C6', 'C7'],
              correctIndex: 0,
              explanation: 'C1, the Atlas, articulates with the occipital condyles of the skull.',
            },
            {
              id: 'anatomy-u2-l1-q5',
              type: 'mcq',
              prompt: 'Which cervical vertebra features the dens (odontoid process), acting as a pivot for rotation?',
              options: ['C1 (Atlas)', 'C2 (Axis)', 'C7', 'C4'],
              correctIndex: 1,
              explanation: 'C2, the Axis, has the dens, which the Atlas pivots around; dens fractures can compromise the spinal cord.',
            },
            {
              id: 'anatomy-u2-l1-q6',
              type: 'true-false',
              prompt: 'The transverse foramen of C7 typically transmits the vertebral artery, just like C1–C6.',
              correctAnswer: false,
              explanation: 'Only accessory veins typically pass through the C7 transverse foramen, not the vertebral artery.',
            },
            {
              id: 'anatomy-u2-l1-q7',
              type: 'mcq',
              prompt: 'Uncovertebral joints (joints of Luschka) are additional joints located between the:',
              options: [
                'Spinous processes of adjacent vertebrae',
                'Bodies of cervical vertebrae',
                'Transverse processes of lumbar vertebrae',
                'Sacrum and ilium',
              ],
              correctIndex: 1,
              explanation: 'Uncovertebral joints provide stability between cervical vertebral bodies but can become a site of bone spur formation.',
            },
            {
              id: 'anatomy-u2-l1-q8',
              type: 'mcq',
              prompt: 'Compared to cervical vertebrae, thoracic vertebral bodies are:',
              options: [
                'Smaller and round, with no rib articulation',
                'Heart-shaped, larger, and have costal facets for rib articulation',
                'Absent a body entirely',
                'The largest in the vertebral column',
              ],
              correctIndex: 1,
              explanation: 'Thoracic bodies are heart-shaped and larger than cervical bodies, with costal facets on the body and transverse processes for rib articulation.',
            },
            {
              id: 'anatomy-u2-l1-q9',
              type: 'mcq',
              prompt: 'Which vertebral region has the largest bodies and intervertebral discs, but the smallest vertebral foramen?',
              options: ['Cervical', 'Thoracic', 'Lumbar', 'Sacral'],
              correctIndex: 2,
              explanation: 'Lumbar vertebrae have the largest bodies/discs (built for weight-bearing) but the smallest vertebral foramen.',
            },
            {
              id: 'anatomy-u2-l1-q10',
              type: 'fill-blank',
              prompt: 'The sacrum is composed of ______ fused vertebrae.',
              acceptedAnswers: ['5', 'five'],
              explanation: 'The sacrum consists of 5 fused vertebrae and serves as an important landmark for pelvic exams.',
            },
            {
              id: 'anatomy-u2-l1-q11',
              type: 'mcq',
              prompt: 'Kyphosis is best described as:',
              options: [
                'Excessive outward curvature of the spine',
                'Excessive inward curvature of the spine',
                'A lateral curvature of the spine',
                'A normal secondary curve',
              ],
              correctIndex: 0,
              explanation: 'Kyphosis is an excessive outward curvature of the spine (hunchback); lordosis is excessive inward curvature.',
            },
            {
              id: 'anatomy-u2-l1-q12',
              type: 'true-false',
              prompt: 'Scoliosis refers to an excessive inward curvature of the spine.',
              correctAnswer: false,
              explanation: 'Scoliosis is a lateral curvature of the spine; excessive inward curvature is lordosis.',
            },
          ],
        },
        {
          id: 'anatomy-u2-l2',
          title: 'Intervertebral Discs & Ligaments',
          questions: [
            {
              id: 'anatomy-u2-l2-q1',
              type: 'mcq',
              prompt: 'The gel-like central substance of an intervertebral disc is the:',
              options: ['Annulus fibrosus', 'Nucleus pulposus', 'Hyaline cartilage plate', 'Ligamentum flavum'],
              correctIndex: 1,
              explanation: 'The nucleus pulposus is the gel-like center of the intervertebral disc.',
            },
            {
              id: 'anatomy-u2-l2-q2',
              type: 'mcq',
              prompt: 'The outer layers of fibrocartilage that surround the nucleus pulposus form the:',
              options: ['Annulus fibrosus', 'Ligamentum flavum', 'Dura mater', 'Costal facet'],
              correctIndex: 0,
              explanation: 'The annulus fibrosus is composed of layers of fibrocartilage surrounding the nucleus pulposus.',
            },
            {
              id: 'anatomy-u2-l2-q3',
              type: 'mcq',
              prompt: 'Cervical intervertebral discs are primarily designed for:',
              options: ['Weight-bearing', 'Motion', 'Shock absorption of the skull only', 'Nerve protection'],
              correctIndex: 1,
              explanation: 'Cervical discs are designed for motion, while lumbar discs are designed for weight-bearing.',
            },
            {
              id: 'anatomy-u2-l2-q4',
              type: 'mcq',
              prompt: 'Lumbar intervertebral discs are primarily designed for:',
              options: ['Motion', 'Weight-bearing', 'Rotation only', 'Housing the dens'],
              correctIndex: 1,
              explanation: 'Lumbar discs are designed for weight-bearing, consistent with the large lumbar vertebral bodies.',
            },
            {
              id: 'anatomy-u2-l2-q5',
              type: 'mcq',
              prompt: 'Which ligament runs along the front of the vertebral bodies?',
              options: ['Posterior longitudinal ligament', 'Anterior longitudinal ligament', 'Ligamentum flavum', 'Nuchal ligament'],
              correctIndex: 1,
              explanation: 'The anterior longitudinal ligament runs along the anterior aspect of the vertebral bodies.',
            },
            {
              id: 'anatomy-u2-l2-q6',
              type: 'mcq',
              prompt: 'Which ligament is the only one that resists extension, and blends into the annulus fibrosus?',
              options: ['Anterior longitudinal ligament', 'Posterior longitudinal ligament', 'Ligamentum flavum', 'Supraspinous ligament'],
              correctIndex: 1,
              explanation: 'The posterior longitudinal ligament is the only ligament that resists extension and blends into the annulus fibrosus.',
            },
            {
              id: 'anatomy-u2-l2-q7',
              type: 'mcq',
              prompt: 'The ligamentum flavum connects:',
              options: ['Adjacent spinous processes', 'Adjacent laminae', 'Adjacent transverse processes', 'The sacrum to the coccyx'],
              correctIndex: 1,
              explanation: 'The ligamentum flavum connects adjacent laminae.',
            },
            {
              id: 'anatomy-u2-l2-q8',
              type: 'mcq',
              prompt: 'Which ligament is an especially important stabilizer of the cervical spine?',
              options: ['Nuchal ligament', 'Anterior longitudinal ligament', 'Iliolumbar ligament', 'Sacrotuberous ligament'],
              correctIndex: 0,
              explanation: 'The nuchal ligament is an important cervical stabilizer.',
            },
            {
              id: 'anatomy-u2-l2-q9',
              type: 'fill-blank',
              prompt: 'The supraspinous and interspinous ligaments stabilize the ______ column of the spine.',
              acceptedAnswers: ['posterior'],
              explanation: 'Supraspinous and interspinous ligaments stabilize the posterior column.',
            },
            {
              id: 'anatomy-u2-l2-q10',
              type: 'true-false',
              prompt: 'By naming convention, an intervertebral disc is named for the vertebra below it.',
              correctAnswer: false,
              explanation: 'Discs are named for the vertebra above them; nerve root symptoms typically stem from the disc above that vertebral body.',
            },
          ],
        },
        {
          id: 'anatomy-u2-l3',
          title: 'Spinal Cord & Meninges',
          questions: [
            {
              id: 'anatomy-u2-l3-q1',
              type: 'mcq',
              prompt: 'From outermost to innermost, what is the correct order of the meningeal layers?',
              options: [
                'Pia mater, arachnoid mater, dura mater',
                'Dura mater, arachnoid mater, pia mater',
                'Arachnoid mater, dura mater, pia mater',
                'Dura mater, pia mater, arachnoid mater',
              ],
              correctIndex: 1,
              explanation: 'From outermost to innermost: dura mater, arachnoid mater, pia mater.',
            },
            {
              id: 'anatomy-u2-l3-q2',
              type: 'mcq',
              prompt: 'Denticulate ligaments are extensions of which meningeal layer, and what do they do?',
              options: [
                'Dura mater; anchor the cord longitudinally',
                'Arachnoid mater; suspend the cord in CSF',
                'Pia mater; stabilize the cord laterally',
                'Pia mater; anchor the cord to the coccyx',
              ],
              correctIndex: 2,
              explanation: 'Denticulate ligaments are extensions of the pia mater that stabilize the spinal cord laterally.',
            },
            {
              id: 'anatomy-u2-l3-q3',
              type: 'mcq',
              prompt: 'The filum terminale is an extension of the pia mater that:',
              options: [
                'Stabilizes the cord laterally',
                'Anchors the cord longitudinally, to the coccyx',
                'Produces cerebrospinal fluid',
                'Forms the outermost protective layer of the cord',
              ],
              correctIndex: 1,
              explanation: 'The filum terminale anchors the spinal cord longitudinally, passing through the sacral hiatus to anchor to the coccyx.',
            },
            {
              id: 'anatomy-u2-l3-q4',
              type: 'mcq',
              prompt: 'During a lumbar puncture, which structure is pierced immediately before the ligamentum flavum?',
              options: ['Supraspinous ligament', 'Interspinous ligament', 'Dura mater', 'Arachnoid mater'],
              correctIndex: 1,
              explanation: 'Needle path: skin → fat → supraspinous ligament → interspinous ligament → ligamentum flavum → dura mater → arachnoid mater → subarachnoid space.',
            },
            {
              id: 'anatomy-u2-l3-q5',
              type: 'mcq',
              prompt: 'During a lumbar puncture, which ligament is pierced FIRST, immediately after the skin and fat?',
              options: ['Ligamentum flavum', 'Interspinous ligament', 'Supraspinous ligament', 'Anterior longitudinal ligament'],
              correctIndex: 2,
              explanation: 'The needle passes through skin, then fat, then the supraspinous ligament first among the ligaments.',
            },
            {
              id: 'anatomy-u2-l3-q6',
              type: 'true-false',
              prompt: 'During a lumbar puncture, the needle passes through the dura mater before reaching the ligamentum flavum.',
              correctAnswer: false,
              explanation: 'The ligamentum flavum is pierced before the dura mater: ...interspinous ligament → ligamentum flavum → dura mater → arachnoid mater.',
            },
            {
              id: 'anatomy-u2-l3-q7',
              type: 'mcq',
              prompt: 'During a lumbar puncture, cerebrospinal fluid (CSF) is collected once the needle reaches the:',
              options: ['Epidural space', 'Subarachnoid space', 'Central canal only', 'Subdural space'],
              correctIndex: 1,
              explanation: 'CSF is found in the subarachnoid space, the final structure reached in the needle path.',
            },
            {
              id: 'anatomy-u2-l3-q8',
              type: 'mcq',
              prompt: 'Which pial extension stabilizes the spinal cord laterally, as opposed to longitudinally?',
              options: ['Filum terminale', 'Denticulate ligaments', 'Ligamentum flavum', 'Nuchal ligament'],
              correctIndex: 1,
              explanation: 'Denticulate ligaments stabilize the cord laterally; the filum terminale anchors it longitudinally.',
            },
            {
              id: 'anatomy-u2-l3-q9',
              type: 'mcq',
              prompt: 'Which meningeal layer is the toughest, outermost layer?',
              options: ['Pia mater', 'Arachnoid mater', 'Dura mater', 'Periosteum'],
              correctIndex: 2,
              explanation: 'The dura mater is the tough, outermost meningeal layer.',
            },
          ],
        },
        {
          id: 'anatomy-u2-l4',
          title: 'Back Musculature & Innervation',
          questions: [
            {
              id: 'anatomy-u2-l4-q1',
              type: 'mcq',
              prompt: 'Superficial (extrinsic) back muscles, associated with limb movement, are innervated by:',
              options: ['Dorsal rami', 'Anterior rami', 'The suboccipital nerve only', 'Cranial nerves'],
              correctIndex: 1,
              explanation: 'Superficial/extrinsic back muscles are associated with limb movement and innervated by anterior rami.',
            },
            {
              id: 'anatomy-u2-l4-q2',
              type: 'mcq',
              prompt: 'Intrinsic (deep) back muscles, associated with spinal stability and movement, are innervated by:',
              options: ['Anterior rami', 'Dorsal rami', 'Phrenic nerve', 'Vertebral artery branches'],
              correctIndex: 1,
              explanation: 'Intrinsic/deep back muscles are innervated by dorsal (posterior) rami.',
            },
            {
              id: 'anatomy-u2-l4-q3',
              type: 'true-false',
              prompt: 'Superficial back muscles are primarily associated with spinal stability, while intrinsic muscles are primarily associated with limb movement.',
              correctAnswer: false,
              explanation: 'It is the reverse: superficial (extrinsic) muscles move the limbs, while intrinsic (deep) muscles stabilize/move the spine.',
            },
            {
              id: 'anatomy-u2-l4-q4',
              type: 'mcq',
              prompt: 'Splenius capitis and splenius cervicis, which function in rotation and extension, belong to which intrinsic muscle group?',
              options: ['Erector spinae', 'Transversospinalis', 'Spinotransversalis', 'Segmental group'],
              correctIndex: 2,
              explanation: 'Splenius capitis and splenius cervicis make up the spinotransversalis group.',
            },
            {
              id: 'anatomy-u2-l4-q5',
              type: 'multi-select',
              prompt: 'Which muscles make up the erector spinae group?',
              options: ['Spinalis', 'Longissimus', 'Iliocostalis', 'Multifidus'],
              correctIndices: [0, 1, 2],
              explanation: 'The erector spinae group includes spinalis, longissimus, and iliocostalis; multifidus belongs to the transversospinalis group instead.',
            },
            {
              id: 'anatomy-u2-l4-q6',
              type: 'mcq',
              prompt: 'The transversospinalis group (semispinalis, multifidus, rotators) functions primarily to produce rotation to the:',
              options: ['Same (ipsilateral) side', 'Opposite (contralateral) side', 'Midline only', 'Cranial direction only'],
              correctIndex: 1,
              explanation: 'The transversospinalis group functions in rotation to the contralateral side.',
            },
            {
              id: 'anatomy-u2-l4-q7',
              type: 'mcq',
              prompt: 'Interspinales and intertransversarii belong to which intrinsic back muscle classification?',
              options: ['Spinotransversalis', 'Erector spinae', 'Transversospinalis', 'Segmental'],
              correctIndex: 3,
              explanation: 'Interspinales and intertransversarii make up the segmental muscle group.',
            },
            {
              id: 'anatomy-u2-l4-q8',
              type: 'multi-select',
              prompt: 'Which muscles form the suboccipital muscle group?',
              options: ['Rectus capitis posterior (major/minor)', 'Obliquus capitis (superior/inferior)', 'Splenius capitis', 'Multifidus'],
              correctIndices: [0, 1],
              explanation: 'The suboccipital muscles are rectus capitis posterior major/minor and obliquus capitis superior/inferior.',
            },
            {
              id: 'anatomy-u2-l4-q9',
              type: 'multi-select',
              prompt: 'The suboccipital triangle, defined by the suboccipital muscles, contains which structures?',
              options: ['Vertebral artery', 'Suboccipital nerve', 'Phrenic nerve', 'Filum terminale'],
              correctIndices: [0, 1],
              explanation: 'The suboccipital triangle contains the vertebral artery and the suboccipital nerve.',
            },
          ],
        },
      ],
    },
    { id: 'anatomy-u3', title: 'Unit 3: Posterior Cervical Triangle, Axillary Region', lessons: [{ id: 'anatomy-u3-l1', title: 'Unit 3: Posterior Cervical Triangle, Axillary Region', questions: [] }] },
    { id: 'anatomy-u4', title: 'Unit 4: Axioappendicular Muscles, Shoulder Joint', lessons: [{ id: 'anatomy-u4-l1', title: 'Unit 4: Axioappendicular Muscles, Shoulder Joint', questions: [] }] },
    { id: 'anatomy-u5', title: 'Unit 5: The Arm, Elbow, Cubital Fossa', lessons: [{ id: 'anatomy-u5-l1', title: 'Unit 5: The Arm, Elbow, Cubital Fossa', questions: [] }] },
    { id: 'anatomy-u6', title: 'Unit 6: Forearm, Wrist', lessons: [{ id: 'anatomy-u6-l1', title: 'Unit 6: Forearm, Wrist', questions: [] }] },
    { id: 'anatomy-u7', title: 'Unit 7: The Hand', lessons: [{ id: 'anatomy-u7-l1', title: 'Unit 7: The Hand', questions: [] }] },
    { id: 'anatomy-u8', title: 'Unit 8: Anterior Neck, Face, TMJ', lessons: [{ id: 'anatomy-u8-l1', title: 'Unit 8: Anterior Neck, Face, TMJ', questions: [] }] },
    { id: 'anatomy-u9', title: 'Unit 9: The Thorax', lessons: [{ id: 'anatomy-u9-l1', title: 'Unit 9: The Thorax', questions: [] }] },
    { id: 'anatomy-u10', title: 'Unit 10: Abdominal Wall, Viscera, Vasculature', lessons: [{ id: 'anatomy-u10-l1', title: 'Unit 10: Abdominal Wall, Viscera, Vasculature', questions: [] }] },
    { id: 'anatomy-u11', title: 'Unit 11: Posterior Abdominal Wall, Pelvis, Gluteal Region', lessons: [{ id: 'anatomy-u11-l1', title: 'Unit 11: Posterior Abdominal Wall, Pelvis, Gluteal Region', questions: [] }] },
    { id: 'anatomy-u12', title: 'Unit 12: Hip, Thigh, Knee', lessons: [{ id: 'anatomy-u12-l1', title: 'Unit 12: Hip, Thigh, Knee', questions: [] }] },
    { id: 'anatomy-u13', title: 'Unit 13: Leg, Foot, Ankle', lessons: [{ id: 'anatomy-u13-l1', title: 'Unit 13: Leg, Foot, Ankle', questions: [] }] },
  ],
};
