import { Topic } from './types';

export const differentialDiagnosis: Topic = {
  id: 'differential-diagnosis',
  title: 'Differential Diagnosis',
  shortTitle: 'Diff Dx',
  description: 'Clinical reasoning and red-flag screening',
  icon: '🧠',
  color: '#FF9600',
  lessons: [
    {
      id: 'diffdx-1',
      title: 'Red Flags & Screening',
      questions: [
        {
          id: 'diffdx-1-1',
          type: 'mcq',
          prompt: 'A patient with new-onset low back pain reports unexplained weight loss, night pain unrelieved by rest, and a history of cancer. This warrants:',
          options: [
            'Continue PT and monitor',
            'Immediate physician referral for possible serious pathology',
            'Ice and heat education only',
            'Reassure and discharge',
          ],
          correctIndex: 1,
          explanation: 'These are classic red flags for malignancy/systemic disease requiring medical referral.',
        },
        {
          id: 'diffdx-1-2',
          type: 'true-false',
          prompt: 'Saddle anesthesia with bowel/bladder changes in a patient with back pain is a red flag for cauda equina syndrome requiring emergent referral.',
          correctAnswer: true,
        },
        {
          id: 'diffdx-1-3',
          type: 'mcq',
          prompt: 'Which of the following is a yellow flag (psychosocial) rather than a red flag (serious pathology)?',
          options: [
            'Fever and unexplained weight loss',
            'Fear-avoidance beliefs about movement',
            'Progressive neurological deficit',
            'History of trauma with suspected fracture',
          ],
          correctIndex: 1,
          explanation: 'Yellow flags are psychosocial risk factors (fear-avoidance, catastrophizing) for chronic pain/disability.',
        },
        {
          id: 'diffdx-1-4',
          type: 'fill-blank',
          prompt: 'Chest pain, shortness of breath, and diaphoresis during exertion in a patient with cardiac risk factors should raise suspicion for ______ pathology and prompt urgent referral.',
          acceptedAnswers: ['cardiac', 'cardiovascular'],
        },
        {
          id: 'diffdx-1-5',
          type: 'mcq',
          prompt: 'A patient presents with bilateral leg symptoms, gait disturbance, and hand clumsiness. This clinical picture is most consistent with:',
          options: ['Lumbar radiculopathy', 'Cervical myelopathy', 'Peripheral neuropathy', 'Piriformis syndrome'],
          correctIndex: 1,
          explanation: 'Bilateral UE/LE signs with gait/hand involvement suggest cervical spinal cord compression (myelopathy) — a red flag.',
        },
        {
          id: 'diffdx-1-6',
          type: 'true-false',
          prompt: 'A positive family history of a condition alone is generally sufficient to constitute a red flag requiring immediate referral.',
          correctAnswer: false,
          explanation: 'Family history contributes to clinical reasoning but is rarely sufficient alone; it is combined with other findings.',
        },
      ],
    },
    {
      id: 'diffdx-2',
      title: 'Shoulder Differentials',
      questions: [
        {
          id: 'diffdx-2-1',
          type: 'mcq',
          prompt: 'A patient with painful arc between 60-120° of abduction, worse with overhead reaching, most likely has:',
          options: ['Adhesive capsulitis', 'Subacromial impingement', 'AC joint separation', 'Cervical radiculopathy'],
          correctIndex: 1,
          explanation: 'A "painful arc" in the mid-range of abduction is classic for subacromial impingement.',
        },
        {
          id: 'diffdx-2-2',
          type: 'mcq',
          prompt: 'A patient with progressive, global loss of both active AND passive shoulder ROM over months, with a capsular pattern, most likely has:',
          options: ['Rotator cuff tear', 'Adhesive capsulitis (frozen shoulder)', 'Labral tear', 'Biceps tendinopathy'],
          correctIndex: 1,
          explanation: 'Global AROM and PROM loss in a capsular pattern (ER > ABD > IR) is characteristic of adhesive capsulitis.',
        },
        {
          id: 'diffdx-2-3',
          type: 'true-false',
          prompt: 'Shoulder pain that worsens with deep inspiration or is unrelated to movement should raise suspicion for a visceral (e.g., cardiac or diaphragmatic) source.',
          correctAnswer: true,
        },
        {
          id: 'diffdx-2-4',
          type: 'fill-blank',
          prompt: 'Referred shoulder pain in a patient with recent abdominal surgery or gallbladder issues may stem from ______ nerve irritation of the diaphragm.',
          acceptedAnswers: ['phrenic'],
        },
        {
          id: 'diffdx-2-5',
          type: 'mcq',
          prompt: 'A young athlete with anterior shoulder pain, apprehension with abduction/external rotation, and a history of dislocation most likely has:',
          options: ['Adhesive capsulitis', 'Anterior instability', 'AC joint arthritis', 'Cervical radiculopathy'],
          correctIndex: 1,
          explanation: 'Apprehension in the ABER position with a dislocation history is classic for anterior glenohumeral instability.',
        },
        {
          id: 'diffdx-2-6',
          type: 'mcq',
          prompt: 'Pain localized directly over the top of the shoulder, worsened with horizontal adduction (cross-body) and heavy lifting, suggests:',
          options: ['AC joint pathology', 'Biceps tendinopathy', 'Adhesive capsulitis', 'Cervical facet referral'],
          correctIndex: 0,
          explanation: 'AC joint pathology classically presents with focal pain reproduced by cross-body adduction.',
        },
      ],
    },
    {
      id: 'diffdx-3',
      title: 'Low Back & Hip Differentials',
      questions: [
        {
          id: 'diffdx-3-1',
          type: 'mcq',
          prompt: 'Low back pain that centralizes (moves proximally) with repeated lumbar extension, per McKenzie principles, suggests:',
          options: ['A discogenic source amenable to directional preference', 'Facet joint arthropathy only', 'SI joint dysfunction', 'A visceral source'],
          correctIndex: 0,
          explanation: 'Centralization with a directional preference (often extension) supports a discogenic mechanical classification.',
        },
        {
          id: 'diffdx-3-2',
          type: 'true-false',
          prompt: 'Lumbar spinal stenosis classically presents with symptoms that worsen with walking/extension and improve with sitting/flexion (positive shopping cart sign).',
          correctAnswer: true,
        },
        {
          id: 'diffdx-3-3',
          type: 'mcq',
          prompt: 'A patient reports lateral hip pain that is worse when lying on the affected side and with resisted hip abduction. This most likely represents:',
          options: ['Greater trochanteric pain syndrome / gluteal tendinopathy', 'Femoral neck stress fracture', 'Piriformis syndrome', 'True hip osteoarthritis'],
          correctIndex: 0,
          explanation: 'Lateral point tenderness at the greater trochanter with resisted abduction pain suggests gluteal tendinopathy/GTPS.',
        },
        {
          id: 'diffdx-3-4',
          type: 'mcq',
          prompt: 'Deep groin pain with hip flexion/rotation, catching or clicking, in a young active patient suggests:',
          options: ['Hip labral tear', 'Greater trochanteric bursitis', 'Lumbar radiculopathy', 'SI joint dysfunction'],
          correctIndex: 0,
          explanation: 'Anterior groin pain with catching/clicking during flexion-rotation movements is classic for labral pathology/FAI.',
        },
        {
          id: 'diffdx-3-5',
          type: 'fill-blank',
          prompt: 'Sudden, severe "worst headache of life" or thunderclap presentations are red flags requiring emergent referral rather than ______ treatment.',
          acceptedAnswers: ['pt', 'physical therapy', 'conservative'],
        },
        {
          id: 'diffdx-3-6',
          type: 'true-false',
          prompt: 'A limping older adult with progressive night pain at the hip and a history of prostate cancer should be screened for possible bony metastasis before continuing routine PT.',
          correctAnswer: true,
        },
      ],
    },
    {
      id: 'diffdx-4',
      title: 'Knee & Neuro Differentials',
      questions: [
        {
          id: 'diffdx-4-1',
          type: 'mcq',
          prompt: 'Acute knee swelling within minutes of a twisting injury (hemarthrosis) is most suggestive of:',
          options: ['Meniscus tear alone', 'ACL rupture', 'Patellar tendinopathy', 'Osteoarthritis flare'],
          correctIndex: 1,
          explanation: 'Rapid effusion (within 0-2 hours) after trauma suggests hemarthrosis, classically from ACL rupture.',
        },
        {
          id: 'diffdx-4-2',
          type: 'true-false',
          prompt: 'Delayed knee swelling that develops over 24 hours after activity is more typical of a meniscal irritation or synovitis than an acute ligamentous rupture.',
          correctAnswer: true,
        },
        {
          id: 'diffdx-4-3',
          type: 'mcq',
          prompt: 'A patient with anterior knee pain worse with prolonged sitting ("theater sign") and stairs, without instability or locking, most likely has:',
          options: ['Meniscus tear', 'Patellofemoral pain syndrome', 'ACL insufficiency', 'Popliteal cyst'],
          correctIndex: 1,
          explanation: 'Pain with prolonged flexion (theater sign) and stairs is classic for patellofemoral pain syndrome.',
        },
        {
          id: 'diffdx-4-4',
          type: 'mcq',
          prompt: 'Distinguishing peripheral neuropathy from lumbar radiculopathy is aided most by which finding?',
          options: [
            'Symmetric, stocking-glove distribution of symptoms vs. dermatomal pattern',
            'Presence of any numbness',
            'Patient age alone',
            'Pain intensity on a 0-10 scale',
          ],
          correctIndex: 0,
          explanation: 'Peripheral neuropathy tends to be symmetric/distal (stocking-glove); radiculopathy follows a dermatomal pattern.',
        },
        {
          id: 'diffdx-4-5',
          type: 'fill-blank',
          prompt: 'A positive ______ sign (dorsiflexion of the great toe reproducing pain) can support an upper motor neuron lesion when assessing for myelopathy.',
          acceptedAnswers: ['babinski'],
        },
        {
          id: 'diffdx-4-6',
          type: 'true-false',
          prompt: 'A locked knee that cannot fully extend after a twisting injury may indicate a displaced (bucket-handle) meniscal tear requiring orthopedic referral.',
          correctAnswer: true,
        },
      ],
    },
  ],
};
