import { Topic } from './types';

export const documentation: Topic = {
  id: 'documentation',
  title: 'Documentation',
  shortTitle: 'Docs',
  description: 'SOAP notes and defensible documentation',
  icon: '📝',
  color: '#FF4B4B',
  lessons: [
    {
      id: 'documentation-1',
      title: 'SOAP Note Basics',
      questions: [
        {
          id: 'documentation-1-1',
          type: 'mcq',
          prompt: 'What does the "S" in a SOAP note stand for?',
          options: ['Summary', 'Subjective', 'Screening', 'Status'],
          correctIndex: 1,
          explanation: 'Subjective: the patient\'s own report of symptoms, function, and history.',
        },
        {
          id: 'documentation-1-2',
          type: 'mcq',
          prompt: 'Which of the following belongs in the "Objective" section of a SOAP note?',
          options: [
            'Patient reports pain is 6/10 today',
            'Goniometric measurement: shoulder flexion 0-120°',
            'Clinical impression that the patient has adhesive capsulitis',
            'Plan to progress to resisted exercise next visit',
          ],
          correctIndex: 1,
          explanation: 'Objective = measurable, observable data (ROM, MMT, gait, special tests).',
        },
        {
          id: 'documentation-1-3',
          type: 'true-false',
          prompt: 'The "Assessment" section should include the clinician\'s professional judgment/interpretation of the subjective and objective findings.',
          correctAnswer: true,
        },
        {
          id: 'documentation-1-4',
          type: 'fill-blank',
          prompt: 'The "P" in SOAP stands for ______, which outlines the treatment strategy and next steps.',
          acceptedAnswers: ['plan'],
        },
        {
          id: 'documentation-1-5',
          type: 'mcq',
          prompt: 'A patient states "my knee gives out when I go downstairs." This statement belongs in which section?',
          options: ['Subjective', 'Objective', 'Assessment', 'Plan'],
          correctIndex: 0,
          explanation: 'Direct patient-reported statements belong in the Subjective section.',
        },
        {
          id: 'documentation-1-6',
          type: 'true-false',
          prompt: 'Objective findings should be reproducible and measurable rather than based on clinician opinion.',
          correctAnswer: true,
        },
      ],
    },
    {
      id: 'documentation-2',
      title: 'Defensible Documentation',
      questions: [
        {
          id: 'documentation-2-1',
          type: 'mcq',
          prompt: 'Defensible documentation should justify the skilled need for physical therapy primarily by:',
          options: [
            'Listing every exercise performed with no rationale',
            'Linking objective impairments to functional limitations and the skilled intervention addressing them',
            'Using only subjective pain reports',
            'Copying the previous note verbatim',
          ],
          correctIndex: 1,
          explanation: 'Skilled care documentation must connect impairments, function, and the clinical reasoning behind interventions.',
        },
        {
          id: 'documentation-2-2',
          type: 'true-false',
          prompt: 'It is acceptable to use "copy forward" (cloning) prior notes verbatim without updating patient status, since it saves time.',
          correctAnswer: false,
          explanation: 'Cloning notes without updates is considered poor practice and can be flagged as fraudulent/non-defensible documentation.',
        },
        {
          id: 'documentation-2-3',
          type: 'mcq',
          prompt: 'Which is the best example of a measurable, well-written short-term goal?',
          options: [
            'Patient will feel better in 2 weeks',
            'Patient will improve strength',
            'Patient will increase R shoulder flexion AROM from 90° to 120° in 2 weeks to don a shirt independently',
            'Patient will do more exercises',
          ],
          correctIndex: 2,
          explanation: 'Good goals are specific, measurable, functional, and time-bound.',
        },
        {
          id: 'documentation-2-4',
          type: 'fill-blank',
          prompt: 'Documentation should always be signed and dated, and late entries should be clearly labeled as a ______ entry.',
          acceptedAnswers: ['late'],
        },
        {
          id: 'documentation-2-5',
          type: 'true-false',
          prompt: 'Documentation should include the patient\'s response to treatment (e.g., tolerance, adverse reactions) during the session.',
          correctAnswer: true,
        },
        {
          id: 'documentation-2-6',
          type: 'mcq',
          prompt: 'Medicare and most payers require documentation to justify "medical necessity." This best means:',
          options: [
            'The patient wants therapy',
            'The service requires the skills of a licensed therapist and is reasonable/necessary for the diagnosis',
            'The clinic has availability',
            'The patient has insurance coverage',
          ],
          correctIndex: 1,
          explanation: 'Medical necessity requires skilled, reasonable, and necessary care tied to a diagnosis and functional deficit.',
        },
      ],
    },
    {
      id: 'documentation-3',
      title: 'Goal Writing & Terminology',
      questions: [
        {
          id: 'documentation-3-1',
          type: 'mcq',
          prompt: 'A well-written goal typically follows which structure?',
          options: [
            'Condition, Behavior/Action, Criteria/Timeframe',
            'Only the intervention name',
            'A vague description of improvement',
            'A list of exercises only',
          ],
          correctIndex: 0,
          explanation: 'SMART goals include the condition, the measurable action/behavior, and the criteria/timeframe.',
        },
        {
          id: 'documentation-3-2',
          type: 'fill-blank',
          prompt: 'The abbreviation "WNL" commonly used in documentation stands for "within ______ limits."',
          acceptedAnswers: ['normal'],
        },
        {
          id: 'documentation-3-3',
          type: 'true-false',
          prompt: 'The abbreviation "NWB" stands for "non-weight bearing."',
          correctAnswer: true,
        },
        {
          id: 'documentation-3-4',
          type: 'mcq',
          prompt: 'Which abbreviation indicates a patient can bear weight as tolerated?',
          options: ['NWB', 'PWB', 'WBAT', 'FWB restricted'],
          correctIndex: 2,
          explanation: 'WBAT = weight bearing as tolerated.',
        },
        {
          id: 'documentation-3-5',
          type: 'mcq',
          prompt: 'Long-term goals in a plan of care typically reflect:',
          options: [
            'Daily session-to-session progress notes',
            'The overall functional outcome expected by discharge',
            'Only impairment-level measurements',
            'The therapist\'s personal opinion',
          ],
          correctIndex: 1,
          explanation: 'Long-term goals describe the discharge-level functional outcome; short-term goals are interim steps toward it.',
        },
        {
          id: 'documentation-3-6',
          type: 'fill-blank',
          prompt: 'The abbreviation "MMT" used in documentation stands for manual muscle ______.',
          acceptedAnswers: ['testing', 'test'],
        },
      ],
    },
    {
      id: 'documentation-4',
      title: 'Legal & Billing Considerations',
      questions: [
        {
          id: 'documentation-4-1',
          type: 'true-false',
          prompt: 'The medical record is considered a legal document and can be used in litigation or audits.',
          correctAnswer: true,
        },
        {
          id: 'documentation-4-2',
          type: 'mcq',
          prompt: 'If an error is made in a paper documentation entry, the correct method is to:',
          options: [
            'Use white-out to remove it',
            'Scribble it out completely so it cannot be read',
            'Draw a single line through the error, initial/date it, and write the correction',
            'Tear out the page and rewrite it',
          ],
          correctIndex: 2,
          explanation: 'A single line through the error preserves the original entry while showing the correction, maintaining a legal audit trail.',
        },
        {
          id: 'documentation-4-3',
          type: 'mcq',
          prompt: 'CPT codes in outpatient PT documentation are primarily used to:',
          options: [
            'Describe the patient\'s diagnosis',
            'Bill payers for the specific services/procedures provided',
            'Track patient satisfaction',
            'Replace the need for a plan of care',
          ],
          correctIndex: 1,
          explanation: 'CPT (Current Procedural Terminology) codes identify billed services/interventions for reimbursement.',
        },
        {
          id: 'documentation-4-4',
          type: 'true-false',
          prompt: 'Under HIPAA, protected health information (PHI) shared in documentation should only be accessible to authorized individuals.',
          correctAnswer: true,
        },
        {
          id: 'documentation-4-5',
          type: 'fill-blank',
          prompt: 'A formal re-assessment of a patient\'s progress toward goals, often required periodically by payers, is called a progress ______.',
          acceptedAnswers: ['note', 'report'],
        },
        {
          id: 'documentation-4-6',
          type: 'mcq',
          prompt: 'Which best describes appropriate documentation of informed consent for treatment?',
          options: [
            'It is implied and never needs to be documented',
            'Document that risks, benefits, and alternatives were discussed and the patient agreed to proceed',
            'Only required for surgical procedures',
            'Verbal consent never needs documentation',
          ],
          correctIndex: 1,
          explanation: 'Documenting the informed consent discussion protects both patient autonomy and the clinician legally.',
        },
      ],
    },
  ],
};
