import { Topic } from './types';

export const goniometry: Topic = {
  id: 'goniometry',
  title: 'Goniometry',
  shortTitle: 'Goniometry',
  description: 'Joint ROM measurement and normal values',
  icon: '📐',
  color: '#1CB0F6',
  units: [
    {
      id: 'goniometry-unit-1',
      title: 'Goniometry',
      lessons: [
    {
      id: 'goniometry-1',
      title: 'Principles & Setup',
      questions: [
        {
          id: 'goniometry-1-1',
          type: 'mcq',
          prompt: 'In goniometry, the stationary arm of the goniometer should be aligned with:',
          options: ['The moving body segment', 'The proximal (stationary) segment', 'The joint line only', 'The distal segment'],
          correctIndex: 1,
          explanation: 'The stationary arm aligns with the proximal, non-moving segment; the moving arm follows the distal segment.',
        },
        {
          id: 'goniometry-1-2',
          type: 'true-false',
          prompt: 'The axis (fulcrum) of the goniometer should be placed over the estimated axis of joint motion.',
          correctAnswer: true,
        },
        {
          id: 'goniometry-1-3',
          type: 'mcq',
          prompt: 'Which is the standard method for measuring joint ROM used in most clinical settings?',
          options: ['Neutral zero method', 'Endpoint estimation', 'Full circle 360° method', 'Visual estimation only'],
          correctIndex: 0,
          explanation: 'The neutral-zero method (0° is anatomical neutral) is the clinical standard (AAOS).',
        },
        {
          id: 'goniometry-1-4',
          type: 'fill-blank',
          prompt: 'Measuring ROM produced by the patient’s own muscle contraction is called ______ range of motion.',
          acceptedAnswers: ['active'],
        },
        {
          id: 'goniometry-1-5',
          type: 'mcq',
          prompt: 'Passive range of motion (PROM) is typically slightly greater than active range of motion (AROM) because:',
          options: [
            'Passive motion is limited by muscle strength',
            'Passive motion is limited by the joint capsule and connective tissue, not contractile force',
            'PROM is always less accurate than AROM',
            'PROM includes muscle recruitment',
          ],
          correctIndex: 1,
          explanation: 'PROM depends on tissue extensibility, not muscle contraction, so it is often slightly greater than AROM.',
        },
        {
          id: 'goniometry-1-6',
          type: 'true-false',
          prompt: 'A firm, springy end-feel at the knee during passive extension is a normal end-feel.',
          correctAnswer: true,
          explanation: 'Normal knee extension has a firm end-feel from capsular/ligamentous tension.',
        },
      ],
    },
    {
      id: 'goniometry-2',
      title: 'Upper Extremity ROM',
      questions: [
        {
          id: 'goniometry-2-1',
          type: 'fill-blank',
          prompt: 'Normal shoulder flexion range is approximately 0 to ______ degrees.',
          acceptedAnswers: ['180'],
        },
        {
          id: 'goniometry-2-2',
          type: 'mcq',
          prompt: 'Normal elbow flexion range of motion is approximately:',
          options: ['0-90°', '0-120°', '0-150°', '0-180°'],
          correctIndex: 2,
          explanation: 'Normal elbow flexion is approximately 0-150°.',
        },
        {
          id: 'goniometry-2-3',
          type: 'mcq',
          prompt: 'When measuring shoulder internal/external rotation, the patient position is typically:',
          options: [
            'Standing, arm at side',
            'Supine, shoulder abducted 90° and elbow flexed 90°',
            'Prone, arm overhead',
            'Sitting, arm fully extended',
          ],
          correctIndex: 1,
          explanation: 'Supine with 90° abduction and 90° elbow flexion standardizes the axis for rotation measurement.',
        },
        {
          id: 'goniometry-2-4',
          type: 'true-false',
          prompt: 'Normal wrist flexion is approximately 80 degrees and wrist extension is approximately 70 degrees.',
          correctAnswer: true,
        },
        {
          id: 'goniometry-2-5',
          type: 'fill-blank',
          prompt: 'Normal forearm supination and pronation are each approximately 0 to ______ degrees.',
          acceptedAnswers: ['80', '80-90', '90'],
        },
        {
          id: 'goniometry-2-6',
          type: 'mcq',
          prompt: 'For shoulder flexion goniometry, the stationary arm is aligned with:',
          options: ['The midline of the humerus', 'The midaxillary line of the thorax', 'The acromion process', 'The sternum'],
          correctIndex: 1,
          explanation: 'The stationary arm aligns with the midaxillary line of the trunk; the axis is at the lateral aspect of the greater tubercle of the humerus.',
        },
      ],
    },
    {
      id: 'goniometry-3',
      title: 'Lower Extremity ROM',
      questions: [
        {
          id: 'goniometry-3-1',
          type: 'mcq',
          prompt: 'Normal hip flexion range of motion (knee flexed) is approximately:',
          options: ['0-90°', '0-120°', '0-140°', '0-160°'],
          correctIndex: 2,
          explanation: 'Normal hip flexion with the knee flexed is approximately 0-120 to 140°.',
        },
        {
          id: 'goniometry-3-2',
          type: 'fill-blank',
          prompt: 'Normal knee flexion range of motion is approximately 0 to ______ degrees.',
          acceptedAnswers: ['135', '140', '150'],
        },
        {
          id: 'goniometry-3-3',
          type: 'true-false',
          prompt: 'Normal ankle dorsiflexion (0-20°) is typically measured with the knee flexed to reduce gastrocnemius tension.',
          correctAnswer: true,
          explanation: 'Knee flexion reduces gastrocnemius influence, isolating soleus/joint restriction on dorsiflexion.',
        },
        {
          id: 'goniometry-3-4',
          type: 'mcq',
          prompt: 'For hip abduction goniometry, the axis of the goniometer is placed over:',
          options: [
            'The greater trochanter',
            'The anterior superior iliac spine (ASIS)',
            'The pubic symphysis',
            'The posterior superior iliac spine (PSIS)',
          ],
          correctIndex: 1,
          explanation: 'The axis is over the ASIS of the extremity being measured for hip abduction.',
        },
        {
          id: 'goniometry-3-5',
          type: 'mcq',
          prompt: 'Normal ankle plantarflexion range of motion is approximately:',
          options: ['0-20°', '0-30°', '0-50°', '0-70°'],
          correctIndex: 2,
          explanation: 'Normal ankle plantarflexion is approximately 0-50°.',
        },
        {
          id: 'goniometry-3-6',
          type: 'true-false',
          prompt: 'Normal hip external rotation and internal rotation are each roughly 45 degrees when measured prone with the knee flexed to 90 degrees.',
          correctAnswer: true,
        },
      ],
    },
    {
      id: 'goniometry-4',
      title: 'End-Feels & Reliability',
      questions: [
        {
          id: 'goniometry-4-1',
          type: 'mcq',
          prompt: 'A hard, abrupt end-feel (bone contacting bone) is best described as which type?',
          options: ['Soft end-feel', 'Firm end-feel', 'Hard end-feel', 'Empty end-feel'],
          correctIndex: 2,
          explanation: 'Hard end-feel = bone-on-bone, e.g., elbow extension.',
        },
        {
          id: 'goniometry-4-2',
          type: 'mcq',
          prompt: 'A patient guards and stops the examiner from moving the joint due to pain, without a true mechanical block. This is called:',
          options: ['Hard end-feel', 'Empty end-feel', 'Springy block', 'Firm end-feel'],
          correctIndex: 1,
          explanation: 'Empty end-feel: motion is limited by pain before tissue resistance is felt.',
        },
        {
          id: 'goniometry-4-3',
          type: 'true-false',
          prompt: 'Soft-tissue approximation (e.g., elbow flexion where bicep meets forearm) is an example of a soft end-feel.',
          correctAnswer: true,
        },
        {
          id: 'goniometry-4-4',
          type: 'mcq',
          prompt: 'Which is generally more reliable in goniometric measurement: intra-rater or inter-rater reliability?',
          options: ['Inter-rater is generally higher', 'Intra-rater is generally higher', 'They are always identical', 'Neither is measurable'],
          correctIndex: 1,
          explanation: 'The same clinician remeasuring (intra-rater) is typically more consistent than different clinicians measuring (inter-rater).',
        },
        {
          id: 'goniometry-4-5',
          type: 'fill-blank',
          prompt: 'A capsular end-feel that is firm but has a slight give, common at the shoulder in external rotation, is called a ______ end-feel.',
          acceptedAnswers: ['firm'],
        },
        {
          id: 'goniometry-4-6',
          type: 'mcq',
          prompt: 'Which factor is LEAST likely to affect goniometric measurement accuracy?',
          options: [
            'Landmark palpation error',
            'Patient effort during AROM',
            'The color of the goniometer',
            'Examiner experience level',
          ],
          correctIndex: 2,
          explanation: 'Goniometer color has no clinical effect on measurement accuracy.',
        },
      ],
    },
      ],
    },
  ],
};
