import { Topic } from './types';

export const hep: Topic = {
  id: 'hep',
  title: 'HEP',
  shortTitle: 'HEP',
  description: 'Home exercise program design and patient education',
  icon: '🏠',
  color: '#2DD4BF',
  lessons: [
    {
      id: 'hep-1',
      title: 'HEP Design Principles',
      questions: [
        {
          id: 'hep-1-1',
          type: 'mcq',
          prompt: 'When designing an effective HEP, the number of exercises should generally be:',
          options: [
            'As many as possible to cover every impairment',
            'Limited to a manageable number to promote adherence',
            'Exactly 10 exercises regardless of the patient',
            'Irrelevant to adherence',
          ],
          correctIndex: 1,
          explanation: 'Fewer, well-chosen exercises improve adherence compared to overwhelming patients with a long list.',
        },
        {
          id: 'hep-1-2',
          type: 'true-false',
          prompt: 'A HEP should be individualized based on the patient\'s impairments, goals, and functional needs rather than using a generic template for every diagnosis.',
          correctAnswer: true,
        },
        {
          id: 'hep-1-3',
          type: 'mcq',
          prompt: 'Which factor is MOST associated with improved HEP adherence?',
          options: [
            'Complex exercises requiring equipment',
            'Clear instructions, appropriate difficulty, and patient buy-in/education on purpose',
            'A long list of unrelated exercises',
            'No follow-up or reassessment',
          ],
          correctIndex: 1,
          explanation: 'Adherence improves with clear instruction, appropriate challenge level, and patient understanding of the "why."',
        },
        {
          id: 'hep-1-4',
          type: 'fill-blank',
          prompt: 'The FITT principle used to prescribe exercise stands for Frequency, Intensity, Time, and ______.',
          acceptedAnswers: ['type'],
        },
        {
          id: 'hep-1-5',
          type: 'mcq',
          prompt: 'For a patient with low literacy or language barriers, the best way to enhance HEP comprehension is to:',
          options: [
            'Use only written instructions in complex medical terminology',
            'Use pictures/diagrams, teach-back method, and simple language',
            'Assume they will figure it out',
            'Skip education entirely',
          ],
          correctIndex: 1,
          explanation: 'Visual aids and the teach-back method improve comprehension across literacy and language barriers.',
        },
        {
          id: 'hep-1-6',
          type: 'true-false',
          prompt: 'Progressing a HEP too quickly without reassessment can increase risk of exacerbating symptoms or injury.',
          correctAnswer: true,
        },
      ],
    },
    {
      id: 'hep-2',
      title: 'Dosage & Progression',
      questions: [
        {
          id: 'hep-2-1',
          type: 'mcq',
          prompt: 'For a strengthening-focused HEP goal, a typical starting dosage recommendation is often:',
          options: ['1 set of 3 reps, max effort', '2-3 sets of 8-12 reps at moderate resistance', '10 sets of 1 rep', 'Continuous exercise for 60 minutes'],
          correctIndex: 1,
          explanation: 'Moderate resistance training for strength gains is commonly 2-3 sets of 8-12 reps, individualized to the patient.',
        },
        {
          id: 'hep-2-2',
          type: 'true-false',
          prompt: 'For a HEP focused on improving muscular endurance, higher repetitions with lower resistance are generally used compared to a strength-focused program.',
          correctAnswer: true,
        },
        {
          id: 'hep-2-3',
          type: 'mcq',
          prompt: 'The principle stating that the body adapts specifically to the type of demand placed on it is called:',
          options: ['Overload principle', 'SAID principle (Specific Adaptation to Imposed Demand)', 'Reversibility principle', 'FITT principle'],
          correctIndex: 1,
          explanation: 'SAID: the body adapts specifically to the type of training stimulus applied.',
        },
        {
          id: 'hep-2-4',
          type: 'fill-blank',
          prompt: 'To continue making strength gains over time, a HEP must apply the principle of progressive ______.',
          acceptedAnswers: ['overload'],
        },
        {
          id: 'hep-2-5',
          type: 'mcq',
          prompt: 'A patient reports 8/10 pain during a HEP exercise that was previously well-tolerated at 2/10. The most appropriate action is to:',
          options: [
            'Have them push through the pain regardless',
            'Modify or regress the exercise and reassess before progressing further',
            'Immediately discontinue all physical activity permanently',
            'Ignore it since HEPs never change',
          ],
          correctIndex: 1,
          explanation: 'A significant increase in pain warrants modification/regression and clinical reassessment.',
        },
        {
          id: 'hep-2-6',
          type: 'true-false',
          prompt: 'Detraining (loss of fitness/strength gains) can begin to occur when exercise stimulus is stopped or significantly reduced for an extended period, per the reversibility principle.',
          correctAnswer: true,
        },
      ],
    },
    {
      id: 'hep-3',
      title: 'Exercise Selection by Goal',
      questions: [
        {
          id: 'hep-3-1',
          type: 'mcq',
          prompt: 'For a post-op ACL reconstruction patient in early rehab (weeks 1-2), an appropriate HEP goal is typically:',
          options: [
            'Return to sport plyometrics',
            'Restore knee extension ROM, reduce swelling, activate quadriceps',
            'Heavy resisted squats',
            'Maximal single-leg hop testing',
          ],
          correctIndex: 1,
          explanation: 'Early post-op ACL rehab prioritizes ROM (especially full extension), edema control, and quad activation.',
        },
        {
          id: 'hep-3-2',
          type: 'true-false',
          prompt: 'Balance/proprioceptive exercises (e.g., single-leg stance) are appropriate to include in a fall-prevention HEP for an older adult.',
          correctAnswer: true,
        },
        {
          id: 'hep-3-3',
          type: 'mcq',
          prompt: 'For a patient with mechanical low back pain who centralizes with extension, a HEP would most appropriately include:',
          options: [
            'Repeated flexion-based exercises only',
            'Prone press-ups / extension-biased exercises per directional preference',
            'Complete bed rest',
            'High-impact plyometrics',
          ],
          correctIndex: 1,
          explanation: 'Directional preference exercises matching the patient\'s centralizing movement (extension) are appropriate.',
        },
        {
          id: 'hep-3-4',
          type: 'fill-blank',
          prompt: 'Exercises like heel raises and eccentric loading are commonly prescribed in a HEP for ______ tendinopathy.',
          acceptedAnswers: ['achilles'],
        },
        {
          id: 'hep-3-5',
          type: 'mcq',
          prompt: 'A HEP for a patient with rotator cuff-related shoulder pain should generally avoid which of the following early on?',
          options: [
            'Pain-free scapular stabilization exercises',
            'Aggressive overhead loading into a painful arc',
            'Isometric rotator cuff activation',
            'Gentle pendulum exercises',
          ],
          correctIndex: 1,
          explanation: 'Loading into a painful impingement arc early on can aggravate symptoms; gradual, pain-guided progression is preferred.',
        },
        {
          id: 'hep-3-6',
          type: 'true-false',
          prompt: 'Aerobic/cardiovascular exercise can be an appropriate component of a HEP for chronic pain management, not just strength-focused conditions.',
          correctAnswer: true,
        },
      ],
    },
    {
      id: 'hep-4',
      title: 'Patient Education & Safety',
      questions: [
        {
          id: 'hep-4-1',
          type: 'mcq',
          prompt: 'The "teach-back" method involves:',
          options: [
            'The therapist repeating instructions multiple times without checking understanding',
            'Asking the patient to explain or demonstrate the exercise back to confirm understanding',
            'Giving the patient a written handout only',
            'Skipping education if the patient nods',
          ],
          correctIndex: 1,
          explanation: 'Teach-back confirms comprehension by having the patient demonstrate/explain instructions in their own words.',
        },
        {
          id: 'hep-4-2',
          type: 'true-false',
          prompt: 'Providing a rationale ("why") for each HEP exercise generally improves patient motivation and adherence compared to instructions alone.',
          correctAnswer: true,
        },
        {
          id: 'hep-4-3',
          type: 'mcq',
          prompt: 'For a cardiac patient starting a home walking program, an important safety education point is to:',
          options: [
            'Exercise through chest pain or dizziness',
            'Recognize warning signs (chest pain, dizziness, unusual shortness of breath) and stop/seek help if they occur',
            'Avoid all physical activity indefinitely',
            'Ignore heart rate response entirely',
          ],
          correctIndex: 1,
          explanation: 'Patient education on warning signs and when to stop is a key safety component of a cardiac HEP.',
        },
        {
          id: 'hep-4-4',
          type: 'fill-blank',
          prompt: 'Reassessing and updating a HEP at follow-up visits based on patient progress is an example of applying the principle of ______ overload appropriately over time.',
          acceptedAnswers: ['progressive'],
        },
        {
          id: 'hep-4-5',
          type: 'mcq',
          prompt: 'Which is the best practice when providing written HEP handouts?',
          options: [
            'Include images/diagrams, clear reps/sets/frequency, and plain-language instructions',
            'Use only medical terminology for accuracy',
            'Omit sets and reps so the patient can decide',
            'Provide no visuals, text only',
          ],
          correctIndex: 0,
          explanation: 'Clear visuals plus plain-language dosage instructions improve usability and adherence.',
        },
        {
          id: 'hep-4-6',
          type: 'true-false',
          prompt: 'A HEP should include instructions on what to do (e.g., modify or stop and contact the clinic) if the patient experiences a significant increase in symptoms.',
          correctAnswer: true,
        },
      ],
    },
  ],
};
