import { Topic } from './types';

export const specialTests: Topic = {
  id: 'special-tests',
  title: 'Special Tests',
  shortTitle: 'Sp. Tests',
  description: 'Orthopedic special tests and their significance',
  icon: '🔍',
  color: '#CE82FF',
  units: [
    {
      id: 'special-tests-unit-1',
      title: 'Special Tests',
      lessons: [
    {
      id: 'special-tests-1',
      title: 'Knee Tests',
      questions: [
        {
          id: 'special-tests-1-1',
          type: 'mcq',
          prompt: 'The Lachman test primarily assesses the integrity of which structure?',
          options: ['PCL', 'ACL', 'MCL', 'Medial meniscus'],
          correctIndex: 1,
          explanation: 'Lachman test (20-30° knee flexion, anterior tibial translation) is the most sensitive test for ACL integrity.',
        },
        {
          id: 'special-tests-1-2',
          type: 'mcq',
          prompt: 'A positive McMurray test with a click/pain during tibial rotation and extension suggests injury to:',
          options: ['ACL', 'PCL', 'Meniscus', 'LCL'],
          correctIndex: 2,
          explanation: 'McMurray test detects meniscal tears via rotation and compression while extending the knee.',
        },
        {
          id: 'special-tests-1-3',
          type: 'true-false',
          prompt: 'The posterior drawer test assesses the posterior cruciate ligament (PCL).',
          correctAnswer: true,
        },
        {
          id: 'special-tests-1-4',
          type: 'mcq',
          prompt: 'The valgus stress test at 0° and 30° of knee flexion primarily assesses:',
          options: ['LCL and posterolateral corner', 'MCL', 'ACL', 'Meniscus'],
          correctIndex: 1,
          explanation: 'Valgus stress tests the MCL; laxity at 30° suggests MCL injury, laxity at 0° suggests more severe/combined injury.',
        },
        {
          id: 'special-tests-1-5',
          type: 'fill-blank',
          prompt: 'The ______ test checks for a positive "sag" sign indicating PCL laxity, observed with hips and knees flexed to 90°.',
          acceptedAnswers: ['posterior sag', 'sag', 'gravity sag', 'godfrey'],
        },
        {
          id: 'special-tests-1-6',
          type: 'mcq',
          prompt: "Patellar apprehension test is used to assess for suspected:",
          options: ['Patellar tendinopathy', 'Lateral patellar instability', 'Chondromalacia', 'ACL tear'],
          correctIndex: 1,
          explanation: 'Apprehension with lateral patellar glide suggests patellar instability/prior dislocation.',
        },
      ],
    },
    {
      id: 'special-tests-2',
      title: 'Shoulder Tests',
      questions: [
        {
          id: 'special-tests-2-1',
          type: 'mcq',
          prompt: "The Neer impingement test is performed by:",
          options: [
            'Passive internal rotation with arm at side',
            'Passive forward flexion with scapula stabilized, causing greater tuberosity to impinge on acromion',
            'Resisted external rotation at 0° abduction',
            'Horizontal adduction across the chest',
          ],
          correctIndex: 1,
          explanation: 'Neer test: examiner passively flexes the shoulder while stabilizing the scapula to compress subacromial structures.',
        },
        {
          id: 'special-tests-2-2',
          type: 'mcq',
          prompt: 'The empty can (Jobe) test primarily assesses:',
          options: ['Infraspinatus', 'Supraspinatus', 'Subscapularis', 'Biceps tendon'],
          correctIndex: 1,
          explanation: 'Empty can test loads supraspinatus with the arm at 90° abduction, 30° horizontal adduction, thumb down.',
        },
        {
          id: 'special-tests-2-3',
          type: 'true-false',
          prompt: "The Speed's test is used to assess biceps tendon pathology.",
          correctAnswer: true,
          explanation: "Speed's test: resisted shoulder flexion with elbow extended and forearm supinated; pain at bicipital groove suggests tendinopathy.",
        },
        {
          id: 'special-tests-2-4',
          type: 'mcq',
          prompt: "A positive lift-off test (Gerber's test) indicates weakness/tear of which muscle?",
          options: ['Supraspinatus', 'Infraspinatus', 'Subscapularis', 'Teres minor'],
          correctIndex: 2,
          explanation: 'Lift-off test isolates subscapularis by having the patient lift the hand off the lower back.',
        },
        {
          id: 'special-tests-2-5',
          type: 'fill-blank',
          prompt: 'The ______ test is performed by having the patient reach behind the back and up between the scapulae, often combined with Neer/Hawkins to screen for impingement.',
          acceptedAnswers: ['apley scratch', 'apley', 'scratch'],
        },
        {
          id: 'special-tests-2-6',
          type: 'mcq',
          prompt: 'The sulcus sign is used to assess for:',
          options: ['Anterior shoulder instability', 'Inferior shoulder (glenohumeral) instability', 'AC joint pathology', 'Rotator cuff tear'],
          correctIndex: 1,
          explanation: 'A visible sulcus below the acromion with downward traction on the arm indicates inferior glenohumeral laxity.',
        },
      ],
    },
    {
      id: 'special-tests-3',
      title: 'Spine & Nerve Tests',
      questions: [
        {
          id: 'special-tests-3-1',
          type: 'mcq',
          prompt: 'The straight leg raise (SLR) test is used primarily to assess for:',
          options: ['Hip labral tear', 'Lumbar disc herniation / nerve root tension', 'SI joint dysfunction', 'Hamstring strain only'],
          correctIndex: 1,
          explanation: 'SLR reproduces radicular symptoms via neural tension on L4-S1 nerve roots, often the sciatic nerve.',
        },
        {
          id: 'special-tests-3-2',
          type: 'true-false',
          prompt: "Spurling's test is used to assess for cervical radiculopathy.",
          correctAnswer: true,
          explanation: "Spurling's test: cervical extension, lateral flexion, and axial compression toward the symptomatic side reproduces radicular pain.",
        },
        {
          id: 'special-tests-3-3',
          type: 'mcq',
          prompt: 'A positive Tinel sign at the wrist (tapping over the carpal tunnel reproducing tingling) suggests:',
          options: ['Ulnar nerve entrapment', 'Median nerve entrapment (carpal tunnel syndrome)', 'Radial nerve entrapment', 'De Quervain tenosynovitis'],
          correctIndex: 1,
          explanation: "Tinel's sign at the wrist over the median nerve supports a carpal tunnel syndrome diagnosis.",
        },
        {
          id: 'special-tests-3-4',
          type: 'mcq',
          prompt: "Phalen's test is positive when:",
          options: [
            'Resisted wrist extension reproduces lateral elbow pain',
            'Sustained wrist flexion for 60 seconds reproduces median nerve symptoms',
            'Cervical compression reproduces arm pain',
            'Passive SLR reproduces low back pain',
          ],
          correctIndex: 1,
          explanation: "Phalen's test increases carpal tunnel pressure via sustained wrist flexion, reproducing median nerve symptoms.",
        },
        {
          id: 'special-tests-3-5',
          type: 'fill-blank',
          prompt: 'The ______ test assesses sacroiliac joint provocation using posterior-to-anterior pressure through the sacrum with the patient prone (one of the SI joint cluster tests).',
          acceptedAnswers: ['thigh thrust', 'sacral thrust', 'gaenslen', 'compression', 'distraction'],
        },
        {
          id: 'special-tests-3-6',
          type: 'true-false',
          prompt: 'The slump test adds a neural tension component to the straight leg raise by incorporating trunk flexion and cervical flexion.',
          correctAnswer: true,
        },
      ],
    },
    {
      id: 'special-tests-4',
      title: 'Hip & Ankle Tests',
      questions: [
        {
          id: 'special-tests-4-1',
          type: 'mcq',
          prompt: "The FABER (Patrick's) test stands for:",
          options: [
            'Flexion, Abduction, External Rotation',
            'Flexion, Adduction, External Rotation',
            'Flexion, Abduction, Extension, Rotation',
            'Forced Abduction, Bending, External Rotation',
          ],
          correctIndex: 0,
          explanation: 'FABER = Flexion, ABduction, External Rotation; screens for hip and SI joint pathology.',
        },
        {
          id: 'special-tests-4-2',
          type: 'mcq',
          prompt: "A positive Thomas test indicates tightness of which muscle group?",
          options: ['Hamstrings', 'Hip flexors (iliopsoas/rectus femoris)', 'Adductors', 'Gluteus maximus'],
          correctIndex: 1,
          explanation: 'Thomas test: inability to keep the contralateral thigh flat on the table indicates hip flexor tightness.',
        },
        {
          id: 'special-tests-4-3',
          type: 'true-false',
          prompt: "The anterior drawer test at the ankle assesses the anterior talofibular ligament (ATFL).",
          correctAnswer: true,
        },
        {
          id: 'special-tests-4-4',
          type: 'mcq',
          prompt: "The Thompson test is used to assess for rupture of the:",
          options: ['Anterior tibialis tendon', 'Achilles tendon', 'Peroneal tendons', 'Posterior tibialis tendon'],
          correctIndex: 1,
          explanation: 'Squeezing the calf with no plantarflexion response (positive Thompson test) indicates Achilles tendon rupture.',
        },
        {
          id: 'special-tests-4-5',
          type: 'fill-blank',
          prompt: 'The ______ test for femoroacetabular impingement/labral pathology involves passive hip flexion, adduction, and internal rotation (FADIR).',
          acceptedAnswers: ['fadir', 'impingement'],
        },
        {
          id: 'special-tests-4-6',
          type: 'mcq',
          prompt: "The squeeze test at the ankle (compressing the tibia and fibula mid-calf) is used to screen for:",
          options: ['Lateral ankle sprain', 'High ankle sprain / syndesmosis injury', 'Achilles rupture', 'Stress fracture of the calcaneus'],
          correctIndex: 1,
          explanation: 'Pain distally with proximal squeeze suggests syndesmotic (high ankle) injury.',
        },
      ],
    },
      ],
    },
  ],
};
